### PR TITLE
Ignore empty output bundle

### LINKED ISSUE #676: Model fails when output bundle contains no fields
## Description
If for whatever reason one of the output bundles is empty (ie. there are no fields added to it) model will crash with this error:

```
20230703 181812.557 ERROR            PET144 ESMF_FieldBundle.F90:11312 ESMF_FieldBundleGetListAll() Invalid object  -  - fieldbundle does not have a geombase object stored
20230703 181812.557 ERROR            PET144 module_wrt_grid_comp.F90:880 Invalid object  - Passing error in return code
20230703 181812.557 ERROR            PET144 fv3_cap.F90:542 Invalid object  - Passing error in return code
20230703 181812.557 ERROR            PET144 ATM:src/addon/NUOPC/src/NUOPC_ModelBase.F90:700 Invalid object  - Passing error in return code
20230703 181812.557 ERROR            PET144 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:2577 Invalid object  - Phase 'IPDvXp01' Initialize for modelComp 1: ATM did not return
ESMF_SUCCESS
20230703 181812.557 ERROR            PET144 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:1286 Invalid object  - Passing error in return code
20230703 181812.557 ERROR            PET144 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:457 Invalid object  - Passing error in return code
20230703 181812.557 ERROR            PET144 UFS.F90:386 Invalid object  - Aborting UFS
20230703 181812.557 INFO             PET144 Finalizing ESMF
```

For example, if `diag_table` is:

```
20210322.06Z.C96.64bit.non-mono
2021 03 22 06 0 0

"fv3_history",    0,  "hours",  1,  "hours",  "time"
"fv3_history2d",  0,  "hours",  1,  "hours",  "time"

"gfs_dyn",     "ps",          "pressfc",   "fv3_history",    "all",  .false.,  "none",  2

"gfs_phys",    "psurf",       "pressfc",   "fv3_history2d",  "all",  .false.,  "none",  2
```

This happens because all fields that will go to physics output are separated into two bundles, one containing fields that will be interpolated using bilinear interpolation method and another using nearest neighbor method. In the above example, physics file will contain only one field (psurf), and it will be interpolated using a bilinear method, which means the bundle for the nearest neighbor will have no fields.

### To Reproduce:
What compilers/machines are you seeing this with? Intel/Hera
Give explicit steps to reproduce the behavior.
1. clone current develop branch
2. run one of the ufs-weather-model regression tests (for example control_p8) and change diag_table as shown above
4. then, oops, look at the bug

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

## Testing:

1. Have you tested the code changes? On what platforms?

2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change? 
- If the baseline results change, is it expected? Please give brief explanation.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<pr_number>
- associated ufs-weather-model/pull/<pr_number>

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Fix model crash if one or the output bundles does not have any field. 

What bug does it fix, or what feature does it add?  #676
Is a change of answers expected from this PR?  No

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #676

## Testing

How were these changes tested?  
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

N/A

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]
Thanks for the fix, the code changes look good to me. So now if quilt is on and diag_table is empty, the model will not crash, right?

**Comment by DusanJovic-NOAA** [comment]
> Thanks for the fix, the code changes look good to me. So now if quilt is on and diag_table is empty, the model will not crash, right?

diag_table file can not be empty (like zero size), it must have at least these two lines at the beginning, for example:
```
20210322.06Z.C96.64bit.non-mono
2021 03 22 06 0 0
```
but it does not need to have any 'files' or 'fields' specifications.

Also, post must be turned off, unless we add some test to detect that both dyn and phy bundles are not empty, and that both dyn and phy bundles have all necessary fields that post needs. But such a list does not exist, so I do not know how we can check that all post fields are present in both bundles.

**Comment by junwang-noaa** [comment]
Yes, what I mean is that diag_table does not have any output fields.
Can we set dopost to false if all the fieldCount from history bundles are zero? Other than that, I think at this time it's the developers' job to use correct post control file if the history files do not contain enough model fields to produce post products.

**Comment by DusanJovic-NOAA** [comment]
> Yes, what I mean is that diag_table does not have any output fields. Can we set dopost to false if all the fieldCount from history bundles are zero? Other than that, I think at this time it's the developers' job to use correct post control file if the history files do not contain enough model fields to produce post products.

Where should we add such a test? Post gets the fields from output bundles in set_postvars_fv3 routine based on which grid_id it is processing at the moment and whether the bundle is a 'restart' bundle or non-restart bundle. Checking the number of fields in set_postvars_fv3 is probably too late. Adding the check somewhere in the write grid component will require non-trivial logic that loops over all bundles, skip all restart bundles, skip all native grid bundles (because post can nor read native grid fields), and finally skip all bundles on grids (domains) other than one currently being processed. I'm not sure adding all this logic is worth it. Especially since  the criteria whether a bundle is empty or not is not enough to guarantee that the post will have access to all required fields.

**Comment by junwang-noaa** [comment]
OK. I agree with you.
@WenMeng-NOAA just let you know that if developers do not include output fields in the diag_table, they need to turn off inline post (write_dopost: .false.). Model will not check inline post setting from the content in diag_table, it will make model code too messy.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by zach1221** [comment]
Good morning, @BrianCurtis-NOAA . Testing is complete on #1825 . Can you please merge this PR for us?

**Pull request merged**
