### PR TITLE
Create ESMF field attributes using the same kind as field data values

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

This PR updates `add_field_to_phybundle` subroutine in io/FV3GFS_io.F90. The values used for esmf field attributes (`_FillValue` and `missing_value`) must be the same real kind as the field data values, in this case REAL(4) in order to avoid type mismatch checks in PIO library which is used by ESMF I/O module.

### Issue(s) addressed

https://github.com/ufs-community/ufs-weather-model/issues/1564

## Testing

How were these changes tested?   Yes
What compilers / HPCs was it tested with?  Intel/Hera
Are the changes covered by regression tests? Yes  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

- waiting on https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/236

### CODE REVIEW

**Comment by jkbk2004** [comment]
Code change only on fv_nggps_diag.f90 at the cubed sphere fvGFS driver level. The dependency https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/236 was approved. We can go ahead to review and approve for the pr. Downstream ufs-wm regression tests are running well  https://github.com/ufs-community/ufs-weather-model/pull/1566.

**Comment by BrianCurtis-NOAA** [comment]
@DusanJovic-NOAA are ESMF field attributes in r4 to keep computational costs at a minimum? I hate the inconsistency of going between r8 and r4 because it can cause issues in the future, and would like to see all be r4 or all be r8 to cause less issues moving forward.

**Review by junwang-noaa — APPROVED** [review]

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA are ESMF field attributes in r4 to keep computational costs at a minimum? I hate the inconsistency of going between r8 and r4 because it can cause issues in the future, and would like to see all be r4 or all be r8 to cause less issues moving forward.

ESMF attributes must be the same kind as field data, which for the history files is always real(4).

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/236 was merged.

**Pull request merged**
