### PR TITLE
Update upp revision

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
interface.

## Description

This PR will solve the issue addressed in the ufs-weather-model issue #[1973](https://github.com/ufs-community/ufs-weather-model/issues/1973) and read a new variable in the inline post interface.
What bug does it fix, or what feature does it add?  
Is a change of answers expected from this PR?  No.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #[1973](https://github.com/ufs-community/ufs-weather-model/issues/1973)

## Testing

How were these changes tested?  
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Would you mind to combine my upp related updates in your FV3 PR? I ran the  UFS single tests control_p8_intel and regional_control_intel. No baseline changes from inline post outputs in GRIB2. You may look into my testing log /u/wen.meng/noscrub/ufs_test/ufs-weather-model/tests/logs/RegressionTests_wcoss2.log on Dogwood. Thanks!

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Would you mind to combine my upp related updates in your FV3 PR? I ran the UFS single tests control_p8_intel and regional_control_intel. No baseline changes from inline post outputs in GRIB2. You may look into my testing log /u/wen.meng/noscrub/ufs_test/ufs-weather-model/tests/logs/RegressionTests_wcoss2.log on Dogwood. Thanks!

@WenMeng-NOAA I merge this branch with #713

**Comment by WenMeng-NOAA** [comment]
> > @DusanJovic-NOAA Would you mind to combine my upp related updates in your FV3 PR? I ran the UFS single tests control_p8_intel and regional_control_intel. No baseline changes from inline post outputs in GRIB2. You may look into my testing log /u/wen.meng/noscrub/ufs_test/ufs-weather-model/tests/logs/RegressionTests_wcoss2.log on Dogwood. Thanks!
> 
> @WenMeng-NOAA I merge this branch with #713

@DusanJovic-NOAA Thanks! It looks good for me. Should I close this PR now?

**Comment by DusanJovic-NOAA** [comment]
> > > @DusanJovic-NOAA Would you mind to combine my upp related updates in your FV3 PR? I ran the UFS single tests control_p8_intel and regional_control_intel. No baseline changes from inline post outputs in GRIB2. You may look into my testing log /u/wen.meng/noscrub/ufs_test/ufs-weather-model/tests/logs/RegressionTests_wcoss2.log on Dogwood. Thanks!
> > 
> > 
> > @WenMeng-NOAA I merge this branch with #713
> 
> @DusanJovic-NOAA Thanks! It looks good for me. Should I close this PR now?

Keep it open until we merge the other PR

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Comment by DusanJovic-NOAA** [comment]
This PR is combined with #713. Should not be merged.

**Comment by DusanJovic-NOAA** [comment]
Merged via #713

**Pull request closed without merging**
