### PR TITLE
ensure exported zbot field is non-negative for coupling

### LINKED ISSUE #293: "inst_height_lowest" field can have negative values exported to ICE when running coupled.
## Description

The ATM ICs currently used in the coupled model can result in negative values of the field ``inst_height_lowest`` to be exported to the ICE. If these values get mapped to an ICE model point, the ICE model seg faults because it uses the ``inst_height_lowest`` value to calculate ``log(zlvl/zref)`` where ``zlvl`` is the imported height and ``zref=10m``.

## Additional context

This bug is IC dependent. It arose during testing for ufs-weather PR [#537](https://github.com/ufs-community/ufs-weather-model/pull/537). More information and testing can be found in this [thread](https://github.com/ufs-community/ufs-weather-model/issues/388#issuecomment-828559457).

## Output

When compile in debug mode, the following error is produced:

```
forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source
fv3.exe            000000000EFE713E  Unknown               Unknown  Unknown
fv3.exe            000000000F1236C0  Unknown               Unknown  Unknown
fv3.exe            000000000889990B  Unknown               Unknown  Unknown
fv3.exe            000000000E323563  icepack_atmo_mp_a         250  icepack_atmo.F90
fv3.exe            000000000E328B16  icepack_atmo_mp_i         953  icepack_atmo.F90
fv3.exe            000000000E4ADF4F  icepack_therm_ver        2528  icepack_therm_vertical.F90
fv3.exe            000000000E204622  ice_step_mod_mp_s         316  ice_step_mod.F90
fv3.exe            000000000D964591  cice_runmod_mp_ic         213  CICE_RunMod.F90
```

Line 250 in icepack_atmo.F90 is: `` alz  = log(zlvl/zref)``

## Testing:

1. Have you tested the code changes? On what platforms?

Gaea was used for determining why the model was failing with the tested IC.

2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?

This fix will be updated in the associated ufs-weather-model PR. That PR will change baselines for all coupled tests.

## Dependent PRs:

- ufs-weather PR [#537](https://github.com/ufs-community/ufs-weather-model/pull/537)

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

Ensures non-negative zbot and pbot for export to the coupled model. See [dycore PR 102](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/102) for details

### Issue(s) addressed

- fixes #293 
- adds 2 additional suites: suite_FV3_GFS_v16_coupled_noahmp.xml, suite_FV3_GFS_v16_coupled_nsstNoahmp.xml

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@junwang-noaa I don't think there is a corresponding issue for the pbot variable at initialization for a couple of reasons.

1) The ice model uses pbot only to calculate the potential temperature and air density (since these are not provided by ATM). That calculation (which is in the CICE cap) only occurs for pres>0.0. If pres were <0.0, the potential T and air density would be set to zero. These values should probably be changed to 273.15K and 1.2 in the CICE cap. 

2) The ocean model imports the surface pressure, but only after the ocean-lag startup and then averaging of the field over the slow coupling period. The ocean lag itself is probably enough to prevent the ocean from getting an initial value of negative surface pressure.

**Comment by junwang-noaa** [comment]
Thanks for checking that. I checked, we had negative delp (pressure
thickness in a model layer) on some points in some cases. If it is the
whole pressure field, it should be fine.

**Comment by DeniseWorthen** [comment]
@junwang-noaa @JessicaMeixner-NOAA I asked Jiande to try this one line fix w/ one of the P6 cases that failed right away. He tried two separate cases and both have run +10days now with this fix. He also tried one case that failed with "thermo-iteration error" and this fix had no impact. He also noted that for a successful P6 case, the fix changes answers (but still succeeds).

**Comment by junwang-noaa** [comment]
Yes, I do expect this fix changes results.

**Comment by DeniseWorthen** [comment]
Yes, Jiande's results are exactly what I expected.

**Comment by DeniseWorthen** [comment]
Converting this to a draft PR in expectation that a correct solution to the root issue will be found prior to the PR for updating the IC is ready for commit.

**Comment by DeniseWorthen** [comment]
The issue is now fixed using dycore PR GFDL_atmos_cubed_sphere PR [102](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/102)

**Comment by DeniseWorthen** [comment]
There are two extra file changes shown which will be resolved after PR #297 is merged.

**Review by junwang-noaa — COMMENTED** [review]
I will approve after the #297 is committed

**Comment by yangfanglin** [comment]
Since dycore PR102 had been reviewed by Henry, Lucas and Rusty etc and they all approved, I have no other comments to this PR. Jun can approval will be sufficient.

**Review by climbfuji — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@junwang-noaa  In the email chain regarding this issue, there seems to be a proposed modification of the fix? I am unsure whether the code is good to be committed as is or if further modifications are going to be made.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@HelinWei-NOAA the NoahMP ccpp suite files for coupled model are added

**Review by HelinWei-NOAA — APPROVED** [review]

**Review by yangfanglin — APPROVED** [review]
looks good

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
