### PR TITLE
Combine PROD and REPRO build options into 'Release' build type

### LINKED ISSUE #1161: Updating options for ufs-weather-model compile settings
## Description
In the current ufs-weather-model, three options/modes are available for the compile settings: PROD, REPRO and DEBUG. The PROD and DEBUG are currently tested in the ufs-weather-model RT. There are some [discussions](https://github.com/ufs-community/ufs-weather-model/discussions/1138) on the reproducibility of PROD and REPROD modes and updating the compile options to support UFS with operation's performance, reproducibility and accuracy requirements. Here is the final compile settings that we will use in ufs RT tests

1. remove the REPRO mode
2. replace the name PROD with RELEASE
3. update the flags for RELEASE to
a. Get rid of -qopt-prefetch=3 -no-prec-div -no-prec-sqrt options
b. replace -fp-model source with -fp-model consistent
 
## Solution
Implement the suggested compile option changes in ufs-weather-model.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- https://github.com/ufs-community/ufs-weather-model/discussions/1138
- https://github.com/ufs-community/ufs-weather-model/issues/1103

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

Combined PROD and REPRO build modes into 'Release' build type. Now only 'Debug' and 'Release' build type are supported. Both build types must produce bit-for-bit reproducible outputs using different number of threads, mpi tasks, different domain decomposition, have reproducible restarts etc.

See this discussion https://github.com/ufs-community/ufs-weather-model/discussions/1138

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes https://github.com/ufs-community/ufs-weather-model/issues/1161

## Testing

How were these changes tested?  
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NCAR/ccpp-framework/pull/449
- waiting on https://github.com/NCAR/ccpp-physics/pull/909

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
Looks good. I'll send you ccpp-framework and ccpp-physics branches later this week that should go with your PRs.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA Corresponding ccpp-physics and framework PRs:

https://github.com/NCAR/ccpp-framework/pull/449
https://github.com/NCAR/ccpp-physics/pull/909

I tested these two branches with your code and could successfully create a new baseline on Hera (with Intel)

**Comment by DusanJovic-NOAA** [comment]
@climbfuji All ufs tests passed, we are ready to merge this PR, please merge ccpp-framework and ccpp-physics PRs.

**Comment by climbfuji** [comment]
> @climbfuji All ufs tests passed, we are ready to merge this PR, please merge ccpp-framework and ccpp-physics PRs.

@DusanJovic-NOAA Done! New hashes are https://github.com/NCAR/ccpp-framework/commit/c95101b40df4cf7109c3d34651792d89455690bf and https://github.com/NCAR/ccpp-physics/commit/3405ff171d7fa55d6aa7fb45b316146516c6e3ca

**Review by climbfuji — APPROVED** [review]
Please revert `.gitmodules` and update the submodule pointers for ccpp-framework and ccpp-physics.

**Pull request merged**
