### PR TITLE
Remove unused coupled suites

### LINKED ISSUE #282: Reduce number of CCPP suites after ufs-weather-model regression test update
## Description

We currently (2021/04/15) have 68 suites in FV3's `ccpp/suites` directory. It is tedious to make changes to CCPP schemes that then require changing each suite definition file.

## Solution

After the update of the ufs-weather-model regression tests has been completed, I suggest:

1. Identify which suites are used by the regression tests, keep those.
2. For the remaining suites, identify owners and whether these suites are still actively used in development and testing by those individuals or collaborators. If yes, keep, if no, delete.
3. Rinse and repeat every year.

## Alternatives
Let the number of suite definition file grow and grow. 

## Testing:

n/a

## Dependent PRs:

n/a

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

Removes old GFS_v17 suite files for coupled model which are no longer required after the commit of the global P7 regression tests.

### Issue(s) addressed

- fixes #282

## Testing

No testing required

## Dependencies

- waiting on ufs-weather PR [#765](https://github.com/ufs-community/ufs-weather-model/pull/765)

### CODE REVIEW

**Comment by junwang-noaa** [comment]
Do you want to remove the suite_FV3_GFS_v15p2_coupled.xml and suite_FV3_GFS_v15p2_couplednsst.xml too?

**Comment by JessicaMeixner-NOAA** [comment]
> Do you want to remove the suite_FV3_GFS_v15p2_coupled.xml and suite_FV3_GFS_v15p2_couplednsst.xml too?

@bingfu-NOAA are you still using the  suite_FV3_GFS_v15p2_coupled.xml and suite_FV3_GFS_v15p2_couplednsst.xml files?

**Comment by DeniseWorthen** [comment]
These are marked on the [spreadsheet](https://docs.google.com/spreadsheets/d/1oDF_L1pkt-J1engAnD431FhE-q09XtZ78LvrT4wZ1Y8/edit#gid=0) as still being required by the ensemble group.

**Comment by junwang-noaa** [comment]
I am curious, does the ensemble group use the latest model with those
GFSv15p2 suite files or they are using the previous ufs-weather-model
versions with those suite files?

**Review by climbfuji — APPROVED** [review]
Yes, please!

**Comment by bingfu-NOAA** [comment]
@JessicaMeixner-NOAA @junwang-noaa I was using those suites for previous ensemble experiments. You may remove them if those old suites need to be removed, I have a copy so I can still use them later if I want.

**Comment by junwang-noaa** [comment]
@bingfu-NOAA Thanks. By the way, you can always check out old revisions to get these suite files, since we are not testing the physics packages in those suites, we don't know if they are working with the latest code or not.

**Comment by DeniseWorthen** [comment]
Close; changes were added to PR #404

**Pull request closed without merging**
