### PR TITLE
[production/RRFS.v1] Fix improperly assigned fire emissions for ebb_dcycle==1 for retrospectives (NOT operational!)

### PR DESCRIPTION
**Pull request by jordanschnell**
## Description

For ebb_dcycle==1 (retrospective fire emissions), the 3-d emissions were incorrectly assgined assigned at all levels using the surface data.

### Issue(s) addressed

- fixes Issue https://github.com/ufs-community/ccpp-physics/issues/188

## Testing

How were these changes tested?  
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by grantfirl** [comment]
@jordanschnell Please pull in the latest production/RRFS.v1 code for testing.

**Comment by grantfirl** [comment]
@jordanschnell Please revert the changes to .gitmodules and `git add` the latest ccpp/physics commit in production/RRFS.v1: https://github.com/ufs-community/ccpp-physics/commit/d889bae2786b0081337cdbc2f6f78df54aa9929e in preparation for merge.

**Comment by jordanschnell** [comment]
> @jordanschnell Please revert the changes to .gitmodules and `git add` the latest ccpp/physics commit in production/RRFS.v1: [ufs-community/ccpp-physics@d889bae](https://github.com/ufs-community/ccpp-physics/commit/d889bae2786b0081337cdbc2f6f78df54aa9929e) in preparation for merge.

HI @grantfirl ,

Want to be clear on this process - 

For revert the changes to .gitmodules, should I make the change to what it was before, add, and recommit? Or should I be using some form of `git revert`

For adding the latest ccpp/physics commit, is this similar to before, i.e., ("ufs-fork" is ufs-community remote,  "jordan" is my fork)

`git checkout production/RRFS.v1`
`git pull ufs-fork production/RRFS.v1`
`git checkout ebb_dcycle_fix`
`git add ccpp`
`git merge production/RRFS.v1`
`git commit`
`git push -u jordan`

**Comment by grantfirl** [comment]
> > @jordanschnell Please revert the changes to .gitmodules and `git add` the latest ccpp/physics commit in production/RRFS.v1: [ufs-community/ccpp-physics@d889bae](https://github.com/ufs-community/ccpp-physics/commit/d889bae2786b0081337cdbc2f6f78df54aa9929e) in preparation for merge.
> 
> HI @grantfirl ,
> 
> Want to be clear on this process -
> 
> For revert the changes to .gitmodules, should I make the change to what it was before, add, and recommit? Or should I be using some form of `git revert`
> 
> For adding the latest ccpp/physics commit, is this similar to before, i.e., ("ufs-fork" is ufs-community remote, "jordan" is my fork)
> 
> `git checkout production/RRFS.v1` `git pull ufs-fork production/RRFS.v1` `git checkout ebb_dcycle_fix` `git add ccpp` `git merge production/RRFS.v1` `git commit` `git push -u jordan`

All we're wanting to do is get the .gitmodules file back to its original state and point to the latest commit of ccpp/physics. So, I would do it like this:

1. cd into ccpp/physics
2. `git checkout production/RRFS.v1`
3. `git pull ufs-fork production/RRFS.v1`
4. git log - make sure that the commit hash corresponds to https://github.com/ufs-community/ccpp-physics/commit/d889bae2786b0081337cdbc2f6f78df54aa9929e
5. cd up to FV3
6. make sure your `ebb_dcycle_fix` branch is checked out
7. `git add ccpp/physics`
8. Your choice of editing .gitmodules and `git add .gitmodules` or just checking out the file from the production/RRFS.v1 branch `git checkout production/RRFS.v1 -- .gitmodules`
9. `git status` - you should see that ccpp/physics and .gitmodules are modified and added
10. `git commit -m "your commit message"`
11. `git push -u jordan`

**Comment by jordanschnell** [comment]
> 3\. git pull ufs-fork production/RRFS.v1

Done! Thank you so much for the detailed explanation - will make future commits so much easier. 

Now, once this is merged, the same thing for ufs-weather-model (i.e, updating FV3 to latest commit and reverting .gitmodules)?

**Comment by grantfirl** [comment]
@jordanschnell Looks good. @MatthewPyle-NOAA @jkbk2004 This should be ready to review/approve/merge.

**Comment by grantfirl** [comment]
> > 3. git pull ufs-fork production/RRFS.v1
> 
> Done! Thank you so much for the detailed explanation - will make future commits so much easier.
> 
> Now, once this is merged, the same thing for ufs-weather-model (i.e, updating FV3 to latest commit and reverting .gitmodules)?

Yep

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA Can you merge this pr?

**Review by MatthewPyle-NOAA — APPROVED** [review]

**Pull request merged**
