### PR TITLE
UFS-SRW v3.0.0 SciDoc updates

### PR DESCRIPTION
**Pull request by grantfirl**
## Description

This PR updates the scientific documentation in the CCPP physics for UFS-SRW App v3.0.0 release. This should be code comments and text files only and should not have any effect on model results. 

### Issue(s) addressed

https://github.com/ufs-community/ccpp-physics/issues/96

## Testing

See <> for testing information

## Dependencies

waiting on https://github.com/ufs-community/ccpp-physics/pull/91

### CODE REVIEW

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
@zach1221 FYI @ChunxiZhang-NOAA does not work with EMC any more.

**Comment by zach1221** [comment]
> @zach1221 FYI @ChunxiZhang-NOAA does not work with EMC any more.

@BrianCurtis-NOAA right.. I knew that. I guess I can't reject the request now.

**Comment by zach1221** [comment]
@dustinswales @SamuelTrahanNOAA  since Grant is out of office, are one of you able to resolve the conflict with this FV3atm PR and update the ccpp-physics submodule pointer and revert the .gitmodules url, following the merge of ccpp-physics [PR#91](https://github.com/ufs-community/ccpp-physics/pull/91)?

**Comment by SamuelTrahanNOAA** [comment]
Why do you need this PR to be updated? Its changes are obsolete now that the CCPP changes were merged.

**Comment by zach1221** [comment]
> Why do you need this PR to be updated? Its changes are obsolete now that the CCPP changes were merged.

That makes sense. Thanks @SamuelTrahanNOAA . I'll have it closed after 1844 is merged.

**Comment by zach1221** [comment]
Closing this PR, as the changes in ccpp-physics PR #91 have already been merged.

**Pull request closed without merging**
