### PR TITLE
Fix Lambert Conformal Conic mapping in the write component on the southern hemisphere

### LINKED ISSUE #838: Write-component hangs for lambert_conformal regional grids in the southern hemisphere
## Description
Specifying a regional `lambert_conformal` write-component grid in the southern hemisphere causes the forecast model to hang. 

## To Reproduce
Run a custom domain/grid the UFS SRW App that is in the southern hemisphere and uses a lambert_conformal write-component grid.  Here is an example of a custom grid in the SRW App's `config.sh` file that fails (it is over Peru):
```
#
# Define custom grid.
#
GRID_GEN_METHOD="ESGgrid"

ESGgrid_LON_CTR="-75.0"
ESGgrid_LAT_CTR="-12.5"
ESGgrid_DELX="3000.0"
ESGgrid_DELY="3000.0"
ESGgrid_NX="940"
ESGgrid_NY="940"
ESGgrid_WIDE_HALO_WIDTH="6"

DT_ATMOS="45"
LAYOUT_X="20"
LAYOUT_Y="20"
BLOCKSIZE="32"

QUILTING="TRUE"
WRTCMP_write_groups="1"
WRTCMP_write_tasks_per_group=$(( 1*LAYOUT_Y ))
WRTCMP_output_grid="lambert_conformal"
WRTCMP_cen_lon="${ESGgrid_LON_CTR}"
WRTCMP_cen_lat="${ESGgrid_LAT_CTR}"
WRTCMP_stdlat1="${ESGgrid_LAT_CTR}"
WRTCMP_stdlat2="${ESGgrid_LAT_CTR}"
WRTCMP_nx="900"
WRTCMP_ny="900"
WRTCMP_lon_lwr_left="-88.0"
WRTCMP_lat_lwr_left="-24.0"
WRTCMP_dx="${ESGgrid_DELX}"
WRTCMP_dy="${ESGgrid_DELY}"
```
Running with this grid causes the `ufs_model` executable to hang until the `run_fcst` task in the SRW App runs out of wallclock time.

## Tests Conducted
I tried running short forecasts (6 hours; using FV3GFS data for ICs/LBCs; all on Hera) that use `lambert_conformal` write-component grids on the following domains/regions:

1) US Southwest
2) Central Asia
3) Northern Pacific
4) Peru
5) Indian Ocean
6) New Zealand

Cases 1-3 (in the northern hemisphere) worked with the original code, but cases 4-6 (in the southern hemisphere) failed.  These tests can be found on Hera in the directories

`/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/TEST_develop_custom_grids/expt_dirs/orig_code/${EXPT_SUBDIR}`

where `EXPT_SUBDIR` can have one of the following six values:

```
custom_grid_ESG_03km_WRTCMP_LambertConf_CentralAsia
custom_grid_ESG_03km_WRTCMP_LambertConf_IndianOcean
custom_grid_ESG_03km_WRTCMP_LambertConf_NewZealand
custom_grid_ESG_03km_WRTCMP_LambertConf_NorthernPacific
custom_grid_ESG_03km_WRTCMP_LambertConf_Peru
custom_grid_ESG_03km_WRTCMP_LambertConf_USSouthWest
```
The log file for the `run_fcst` task (which calls the `ufs_model` executable) is at `log/run_fcst_2019061500.log` under each experiment directory.  The 3 failed cases just hang during the forecast.

## Possible Solution
I tried changing the Lambert conformal transformation formulas used in the write-component (in `module_wrt_grid_comp.F90`) to ones I use in other codes I have (obtained [here](https://en.wikipedia.org/wiki/Lambert_conformal_conic_projection)).  I then retried the 6 cases above.  All were successful, confirming that the formulas used may have a bug (at least for the southern hemisphere).  The six successful runs with the modified formulas can be found on Hera in the directories:

`/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/TEST_develop_custom_grids/expt_dirs/new_code/${EXPT_SUBDIR}`

The specific modifications I made to the formulas are as follows (where `module_wrt_grid_comp.F90.orig` is the original file and `module_wrt_grid_comp.F90.new` is the file with my changes to the Lambert conformal formulas):

```
$ diff module_wrt_grid_comp.F90.orig module_wrt_grid_comp.F90.new
3638c3638
<             dlon=modulo(glon-c_lon+180+3600,360.)-180.D0
---
>             dlon=glon-c_lon
3644,3645c3644,3645
<             rho = sqrt(x*x+y*y)
<             theta=atan2(x,y)
---
>             rho = sign(1.0,en)*sqrt(x*x+y*y)
>             theta=atan(x/y)
3647,3649c3647
<             glon=modulo(glon+180+3600,360.)-180.D0
< !            glat=(2.0*atan((a*f/rho)**(1.0/en))-0.5*pi)*rtod
<             glat=(0.5*pi-2.0*atan((rho/(a*f))**(1.0/en)))*rtod
---
>             glat=(2.0*atan((a*f/rho)**(1.0/en))-0.5*pi)*rtod
```

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

Subroutine `lambert` in the write component has been fixed to do the mapping on the southern hemisphere correctly.

Is a change of answers expected from this PR?  Yes. due to changes in formulas used for lambert projection 4 tests that output history files on lambert conformal conic grid will be changed.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes https://github.com/ufs-community/ufs-weather-model/issues/838

## Testing

How were these changes tested?   Yes
What compilers / HPCs was it tested with? Intel/Hera  
Are the changes covered by regression tests? Yes.
Have the ufs-weather-model regression test been run? Yes.
On what platform?  Hera
- Will the code updates change regression test baseline? Yes.
- If yes, why? 4 tests that output history files on Lambret projection are different.

### CODE REVIEW

**Comment by gsketefian** [comment]
@DusanJovic-NOAA I just tested your `lambert_sh` branch in the SRW App on the 6 regional domains mentioned in Issue #[838](https://github.com/ufs-community/ufs-weather-model/issues/838).  The domains are:
1. US Southwest
2. Central Asia
3. Northern Pacific
4. Peru
5. Indian Ocean
6. New Zealand

All 6 domains completed workflow end-to-end experiments successfully.   This PR can now be merged.  Thanks.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA I just tested your `lambert_sh` branch in the SRW App on the 6 regional domains mentioned in Issue #[838](https://github.com/ufs-community/ufs-weather-model/issues/838). The domains are:
> 
> 1. US Southwest
> 2. Central Asia
> 3. Northern Pacific
> 4. Peru
> 5. Indian Ocean
> 6. New Zealand
> 
> All 6 domains completed workflow end-to-end experiments successfully. This PR can now be merged. Thanks.

Thank you @gsketefian

**Comment by gsketefian** [comment]
@DusanJovic-NOAA When do you think this PR will get merged?  I need to report back to the EPIC people who are doing the SRW release since they want to cut a release branch of the App pretty soon (and they can't do it before this PR is merged).  Thanks.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA When do you think this PR will get merged? I need to report back to the EPIC people who are doing the SRW release since they want to cut a release branch of the App pretty soon (and they can't do it before this PR is merged). Thanks.

According to the commit queue, it should be merged on March 18.

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
