### PR TITLE
Fix memory errors: uninitialized variables, and NetCDF writes to arrays that are too small

### LINKED ISSUE #667: Uninitialized Grid variables in GFS_typedefs.F90 grid_create
## Description
Several of the Grid% variables are allocated but not initialized in grid_create in the GFS_typedefs.F90

### To Reproduce:

What compilers/machines are you seeing this with?

All.

This was discovered while debugging these problems. I used valgrind on a RRFS gnu regression test with 32-bit physics:

- https://github.com/ufs-community/ccpp-physics/issues/83
- https://github.com/ufs-community/ccpp-physics/issues/84

## Additional context
N/A

## Output
N/A

## Testing:

Tested on hera. There are new regression tests for RRFS with 32-bit physics.

## Dependent PRs:

- ccpp-physics: https://github.com/ufs-community/ccpp-physics/issues/83
- ccpp-physics: https://github.com/ufs-community/ccpp-physics/issues/84
- ccpp-physics: https://github.com/ufs-community/ccpp-physics/issues/85

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Description

This fixes two memory errors detected with valgrind, and one missing error check (errmsg, errflg). See the "issues addressed" for details.

### Issue(s) addressed

- fv3atm: fixes https://github.com/NOAA-EMC/fv3atm/issues/667
- ccpp-physics: https://github.com/ufs-community/ccpp-physics/issues/83
- ccpp-physics: https://github.com/ufs-community/ccpp-physics/issues/84

#### How were these changes tested?  

A 32-bit physics version of the RRFS conus13km regression tests, using valgrind.

#### What compilers / HPCs was it tested with?  

Hera gnu and intel

#### Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  

There are new regression tests

#### Have the ufs-weather-model regression test been run? On what platform?  

Yes. Hera.

#### Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.

No, but there are new tests.

#### Please commit the regression test log files in your ufs-weather-model branch

Will do.

## Dependencies

- waiting on ccpp-physics https://github.com/ufs-community/ccpp-physics/pull/85

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@SamuelTrahanNOAA It looks to me the error-check in https://github.com/ufs-community/ccpp-physics/issues/83 is to prevent the error of read(4) array from reading real(8) data. I am wondering what the solution is, so you will need a new netcdf file with real(4) data in order to run the 32bit physics?

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA It looks to me the error-check in ufs-community/ccpp-physics#83 is to prevent the error of read(4) array from reading real(8) data. I am wondering what the solution is, so you will need a new netcdf file with real(4) data in order to run the 32bit physics?

My fix for the type conversion error was to use the NetCDF Fortran 90 interface. The Fortran 90 interface does automatic type conversion. Previously, that code used the Fortran 77 NetCDF interface.

**Comment by junwang-noaa** [comment]
Got it, thanks

**Review by junwang-noaa — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
Quoting the documentation of `NF90_GET_VAR`,

> Data values are converted from the external type of the variable, if necessary.

They define "external type of a variable" as the type it has in the file. An exception to this rule is string arrays, which have no automatic type conversion.

**Comment by SamuelTrahanNOAA** [comment]
The ccpp-physics PR has been merged. I have update the submodule pointer and reverted the .gitmodules. We're waiting for this PR to be merged so we can finish https://github.com/ufs-community/ufs-weather-model/pull/1797

**Comment by zach1221** [comment]
@jkbk2004 can you merge this PR, please? I'm not authorized in this case.

**Pull request merged**
