### PR TITLE
Release/public-v3: Add WoFS suite definition file for SRW v3 release

### PR DESCRIPTION
**Pull request by MicroTed**
## Description

Adds SDF file suite_FV3_WoFS_v0.xml for SRW public-v3

## Dependencies

Newer CCPP has an update to the NSSL microphysics that fixes a restart and MPI decomposition issues. We can point to a newer commit for that (which needs a couple other updates to work, however).

### CODE REVIEW

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Review by grantfirl — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@MicroTed It looks to me that the ccpp physics in your fv3atm branch pub-v3-wofssdf is pointing to an old revision of ccpp physics public-v6 branch. You may need to update the fv3 submodule  to use the latest ccpp physics publib-v6 branch (revision 7e353513) and run the Wofs test. Also just let you know that your ccpp fixes for the WoFS testsin ccpp physics PR#904 is not in the public-v6 release branch yet. @grantfirl FYI

https://github.com/NCAR/ccpp-physics/commits/release/public-v6

**Comment by grantfirl** [comment]
> @MicroTed It looks to me that the ccpp physics in your fv3atm branch pub-v3-wofssdf is pointing to an old revision of ccpp physics public-v6 branch. You may need to update the fv3 submodule to use the latest ccpp physics publib-v6 branch (revision 7e353513) and run the Wofs test. Also just let you know that your ccpp fixes for the WoFS testsin ccpp physics PR#904 is not in the public-v6 release branch yet. @grantfirl FYI
> 
> https://github.com/NCAR/ccpp-physics/commits/release/public-v6

@junwang-noaa @MicroTed OK, sorry for the delay. Let me update the release/public-v6 branch of ccpp-physics so that this can point to the latest... Stand by.

**Comment by grantfirl** [comment]
@MicroTed @junwang-noaa I've updated the release/public-v6 branch with commits that belong there to the best of my knowledge, including Ted's PR#904 bugfixes in ccpp-physics. The commit at the top of that branch is now: https://github.com/NCAR/ccpp-physics/commit/b3e094483e3b56cf0e4cb463a07cc5deb509779c

I've also noticed that the .gitmodules file in this repo is still pointing to the `main` branch of ccpp-physics rather than `release/public-v6'. I'm guessing this should be updated too?

**Comment by MicroTed** [comment]
> I've also noticed that the .gitmodules file in this repo is still pointing to the `main` branch of ccpp-physics rather than `release/public-v6'. I'm guessing this should be updated too?

Thanks, @grantfirl  I saw that, too. I think that commit 7e3535134 (one scheme one file) has companion changes in framework. If you want me to add all those into this PR, I can do that, or it could be a separate PR and then merge in this one (which only adds the SDF).

**Comment by grantfirl** [comment]
@MicroTed The "one scheme to one file" changes were already in the ccpp-physics release branch before I just updated it. But, you're right that there are changes required for that code. However, the changes are in the fv3atm repo and not the ccpp-framework. This PR (https://github.com/NOAA-EMC/fv3atm/pull/519) should be put into the fv3atm release branch. I'm not sure why it wasn't already there. The PR branch for this change (https://github.com/grantfirl/fv3atm/tree/one_scheme_to_one_file) still exists in my fork, so it should be easy just to merge that branch into [MicroTed:pub-v3-wofssdf](https://github.com/MicroTed/fv3atm/tree/pub-v3-wofssdf) and push back to solve this issue.

Regarding ccpp-framework, it is my understanding that the release is just going to take whatever is in the top of main when the code is really frozen. Nothing that effects how the code generation, etc. works will be changed between now and the release. So, for the purpose of this PR, I would just checkout the latest ccpp-framework main and add it your fv3atm PR branch so that it is at least pointing to the latest.

**Comment by MicroTed** [comment]
@grantfirl  Correct that "one scheme" was there already in public-v6, but the v3 release was pointing to an earlier commit. 
I'll update to the current public-v6 CCPP (and .gitmodules) and ccpp-framework (main). I cherry-picked your corresponding commit that updated ccpp_prebuild_config.py, and it all compiles. I am now running RT for rrfs_v1nssl on hera, then will do the regional_3km_wofs

**Comment by junwang-noaa** [comment]
@ligiabernardet @ChunxiZhang-NOAA Please see the updates in fv3atm/ccpp public_v3 branch. FYI,

**Comment by grantfirl** [comment]
The updates all look correct to me. Thanks, @MicroTed .

**Comment by MicroTed** [comment]
Updates done, and RT/ORT tests run. The dcp test for regional_3km_wofs is successful with nrows_blend=0. (It should fail with nrows_blend=10). (Also updated PR https://github.com/ufs-community/ufs-weather-model/pull/1220 )

**Comment by jkbk2004** [comment]
@MicroTed can you sync up your branch with NOAA-EMC:develop? 8 commits behind NOAA-EMC:develop. so that @daniel-hildebrandt can take next steps for merging.

**Comment by MicroTed** [comment]
>can you sync up your branch with NOAA-EMC:develop? 8 commits behind NOAA-EMC:develop. so that @daniel-hildebrandt can take next steps for merging.

@jkbk2004  That should be fine. Just to be clear, you are wanting the public-v3 to catch up to the current develop branch?

**Comment by jkbk2004** [comment]
> > can you sync up your branch with NOAA-EMC:develop? 8 commits behind NOAA-EMC:develop. so that @daniel-hildebrandt can take next steps for merging.
> 
> @jkbk2004 That should be fine. Just to be clear, you are wanting the public-v3 to catch up to the current develop branch?

@MicroTed I think it depends on the SRW release plan. @daniel-hildebrandt can you make sure release/public-v3 is the one created for srw release and should be synced with develop?

**Comment by jkbk2004** [comment]
> > > can you sync up your branch with NOAA-EMC:develop? 8 commits behind NOAA-EMC:develop. so that @daniel-hildebrandt can take next steps for merging.
> > 
> > 
> > @jkbk2004 That should be fine. Just to be clear, you are wanting the public-v3 to catch up to the current develop branch?
> 
> @MicroTed I think it depends on the SRW release plan. @daniel-hildebrandt can you make sure release/public-v3 is the one created for srw release and should be synced with develop?

@junwang-noaa If we don't need to maintain RT tests with the release/public-v3 branch (SRW tests will be maintained by the SRW group), @daniel-hildebrandt can merge in this PR to the release branch, right? Ted has PR#514 to develop branch. So I think we can follow up separately later.

**Comment by junwang-noaa** [comment]
@jkbk2004 I am not sure who will be testing/maintaining the RT test for CCPP v6 and SRW public release. @grantfirl @ligiabernardet @JeffBeck-NOAA @arunchawla-NOAA FYI.

**Comment by jkbk2004** [comment]
> @jkbk2004 I am not sure who will be testing/maintaining the RT test for CCPP v6 and SRW public release. @grantfirl @ligiabernardet @JeffBeck-NOAA @arunchawla-NOAA FYI.

@junwang-noaa @daniel-hildebrandt For CCPPv6/SRW-release cases, EPIC should support the RT tests. Then, sync release/public-v3 to develop will be much easier way.

**Comment by MicroTed** [comment]
Note that there is a separate PR to add the suite for the release branch:
https://github.com/NOAA-EMC/fv3atm/pull/514
But it has been held up by unrelated ORT issues for the regional.
So I was requested to open a separte PR for v3 to make sure it had the suite.

**Comment by daniel-hildebrandt** [comment]
> Note that there is a separate PR to add the suite for the release branch: #514 But it has been held up by unrelated ORT issues for the regional. So I was requested to open a separte PR for v3 to make sure it had the suite.

@MicroTed Would you be able to verify that this is up-to-date with the release branch? The SRW release team wanted to ensure that the release/branch was up-to-date with develop.

**Comment by jkbk2004** [comment]
> > Note that there is a separate PR to add the suite for the release branch: #514 But it has been held up by unrelated ORT issues for the regional. So I was requested to open a separte PR for v3 to make sure it had the suite.
> 
> @MicroTed Would you be able to verify that this is up-to-date with the release branch? The SRW release team wanted to ensure that the release/branch was up-to-date with develop.

@MicroTed Once pub-v3-wofssdf is synced up to date, we can merge in this PR to release/public-v3.

**Comment by MicroTed** [comment]
I tried merging with develop, but then there are cmake errors (e.g., looks for physics/smoke), so I think CCPP will also need to be updated?

**Comment by jkbk2004** [comment]
> I tried merging with develop, but then there are cmake errors (e.g., looks for physics/smoke), so I think CCPP will also need to be updated?

@MicroTed Your branch is using ccpp/release/public-v6. Can you switch to ccpp/develop? On the other hands, srw/release/public-v2 still points to ccpp/develop (not v6 yet). So, I think it will be ok to merge in your PR with ccpp/develop. @daniel-hildebrandt We need to work on the branch pointer issue of srw/release/public-v2.

**Comment by MicroTed** [comment]
OK, I saw that release/public-v3 had been updated, so I merged to that. So I think (hope) it is up to date now.

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
