### PR TITLE
Switch ccpp-physics submodule

### PR DESCRIPTION
**Pull request by dustinswales**
## Description

This PR contains changes to the CI tests in ccpp-physics. There are no changes to source code.

### CODE REVIEW

**Comment by jkbk2004** [comment]
It's simple yaml file change for ccpp git action. All tests are done on weather model side. @DusanJovic-NOAA @ChunxiZhang-NOAA We can start merging in this pr.

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@dustinswales can you update ccpp hash and revert branch on gitmodules? so that we can merge in this pr here

**Comment by dustinswales** [comment]
@jkbk2004 Done.

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA @BrianCurtis-NOAA Minor change. I am merging in this pr.

**Pull request merged**
