### PR TITLE
Sync support to integrate PR #743 to Use MPI_Bcast instead of multiple p2p messages to update nest

### PR DESCRIPTION
**Pull request by jkbk2004**
## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Provide a detailed description of what this PR does.  
- This PR is replacing #743 due to the sync issue of the PR #743 feature branch 
Is a change of answers expected from this PR?  No 

## Dependencies

Do PRs in upstream repositories need to be merged first?
This PR depends on merging of PR 272 into the GFDL_atmos_cubed_sphere
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/272

### CODE REVIEW

**Comment by jkbk2004** [comment]
#743 looks good now.

**Comment by jkbk2004** [comment]
@dkokron I still see sync issue on your feature branch. Instead of directly fixing on your branch, I am trying to replace #743 with this PR. We are supposed to code changes only in https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/272 @DusanJovic-NOAA @junwang-noaa Can I ask to review and approve?

**Comment by DusanJovic-NOAA** [comment]
What are the sync issues in 743?

**Comment by junwang-noaa** [comment]
@jkbk2004 We have some documentation updates committed to fv3atm, please sync.

**Review by junwang-noaa — APPROVED** [review]

**Comment by dkokron** [comment]
What is the question?

**Comment by DusanJovic-NOAA** [comment]
I do not see the purpose of this PR. I do not see any difference between this PR and #743. We should not create new PRs just to replace the original PR. This just creates confusion.

**Comment by jkbk2004** [comment]
> I do not see the purpose of this PR. I do not see any difference between this PR and #743. We should not create new PRs just to replace the original PR. This just creates confusion.

Closing this pr. I cleaned up unnecessary file changes in #743: atmos_model.F90 module_wrt_grid_comp.F90 fv_moving_nest_main.F90.

**Pull request closed without merging**
