### PR TITLE
STY: Use capital W and lowercase m for watts per square meter

### PR DESCRIPTION
**Pull request by DWesl**
All in W/m**2, one of which was w/m2, so that's consistent now.

## Description

Various places report units of `w/m**2` for flux variables.  This changes those to `W/m**2` to make those units machine-readable.

### Issue(s) addressed

Found the same way as NOAA-GFDL/GFDL_atmos_cubed_sphere#350

## Testing

I made the `w/m**2` -> `W/m**2` changes in a clone of the global-workflow repository, then ran the model and checked the history files, to find most flux variables were now `W/m**2`, none were `w/m**2`, and two were `W/M**2`.  I fixed the last two and haven't checked that result yet.

I checked this using Intel compilers.

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
This PR needs new baselines. @DWesl We need ufs-weather-model PR that includes fv3atm and corresponding atmos_cubed_sphere PRs so that we can generate new baselines and run full regression tests.  I do not see such ufs-wm PR.

**Comment by DWesl** [comment]
Would that mean a commit here updating the atmos_cubed_sphere submodule to point at my branch there, then in ufs-weather-model pointing at this one?  Should I merge the main/develop branches in each PR before doing so?

**Comment by DusanJovic-NOAA** [comment]
> Would that mean a commit here updating the atmos_cubed_sphere submodule to point at my branch there, then in ufs-weather-model pointing at this one? Should I merge the main/develop branches in each PR before doing so?

Yes. Merge your fv3atm and atmos_cubed_sphere branches with the corresponding develop branches so that they are not behind, then update .gitmodules and create ufs-weather-model branch. In the ufs-wm PR indicate that new baselines are required.

**Comment by DWesl** [comment]
Now includes changes from NOAA-GFDL/GFDL_atmos_cubed_sphere#356.

Now included in ufs-community/ufs-weather-model#2467.  There's more steps requested there, but I'm not sure how to complete them.  In particular, I assumed that "new baselines required" corresponded to "PR Adds New Tests/Baselines" rather than "PR Updates Baselines", but I'm not sure how to add or update a test or baseline, nor how to run the RT (regression test?) suite.

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
* Cosmetic unit update: w/m**2 to W/m**2

**Pull request merged**
