### PR TITLE
Move unused ccpp suites to 'suites_not_used' directory

### LINKED ISSUE #510: Move deprecated suite definition files (SDFs) into a 'untested' subdirectory
## Description
Many suite definition files (SDFs) are no longer supported by regression tests (RTs). Therefore, there are high risks that those SDFs will encounter errors when used in applications. We decided to move those SDFs into a 'untested' subdirectory under the ccpp/suites directory. Users can modify and test those deprecated SDFs.  

**The SDFs that will be saved are:**
FV3_GFS_v17_p8
FV3_GFS_v17_p8_rrtmgp
FV3_GFS_v17_coupled_p8
FV3_GFS_v17_coupled_p8_sfcocn
FV3_GFS_v15p2
FV3_GFS_v15_thompson_mynn_lam3km
FV3_GFS_v16
FV3_GFS_v16_csawmg
FV3_GFS_v16_ras
FV3_GFS_v16_fv3wam
FV3_RAP
FV3_RAP_RRTMGP
FV3_RAP_sfcdiff
FV3_RAP_unified_ugwp
FV3_RAP_cires_ugwp
FV3_RAP_flake
FV3_RAP_noah
FV3_RAP_noah_sfcdiff_cires_ugwp
FV3_HRRR
FV3_HRRR_smoke
FV3_RRFS_v1beta
FV3_RRFS_v1nssl
FV3_WoFS_v0
FV3_HAFS_v1_gfdlmp_tedmf
FV3_HAFS_v1_gfdlmp_tedmf_nonsst
FV3_HAFS_v1_thompson_tedmf_gfdlsf
FV3_HAFS_v1_thompson_noahmp_nonsst
FV3_HAFS_v1_thompson_noahmp
FV3_HAFS_v1_thompson_nonsst
FV3_HAFS_v1_thompson

**Those 4 SDFs are compiled but not in any RTs**
FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp
FV3_GFS_v15_thompson_mynn
FV3_GFS_v16_ugwpv1
FV3_GFS_v16_noahmp

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

This PR moves all unused ccpp suite definition files to a separate directory (suites_not_used)
Is a change of answers expected from this PR?  No.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #510

## Testing

How were these changes tested?  Regression test on Hera
What compilers / HPCs was it tested with?  Intel and gnu
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? Yes
On what platform?  Hera
- Will the code updates change regression test baseline? No.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first? No

### CODE REVIEW

**Comment by jkbk2004** [comment]
@grantfirl can you review on this pr to move unused suites to separate directory?

**Comment by jkbk2004** [comment]
Moving old and unused suites to separate directory makes a sense. Please, go ahead to review review comments.

**Review by grantfirl — APPROVED** [review]
Seems fine to me. The reason to move them instead of remove them entirely is because *someone* might be using them for research, etc. that we're unaware of?

**Review by Qingfu-Liu — APPROVED** [review]
good practice

**Comment by FernandoAndrade-NOAA** [comment]
Testing on #[1793](https://github.com/ufs-community/ufs-weather-model/pull/1793) has completed, please go ahead and finalize reviews/approvals and begin the merging process for this PR @BrianCurtis-NOAA @junwang-noaa

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
