### PR TITLE
RRTMG cloud overlap method update

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR adds two new interstitial variables to `GFS_typedefs.{F90,meta}` that are required for the RRTMG cloud overlap additions by @mjiacono (see https://github.com/NCAR/ccpp-physics/pull/487). Other changes:

- fix wrong metadata in `GFS_typedefs.meta` (`optional` and `intent` are not valid for host model variable tables)
- note that RRTMG and RRTMGP use different interstitial variables for the decorrelation parameter `alpha`; this is because RRTMGP only works when the number of model levels is the same for radiation (`levr`) and other physics (`levs`), while RRTMG works with different numbers of levels; only the one in use gets allocated
- replace GSL drag suite with CIRES UGWP/GFS GWD in ccpp/suites/suite_FV3_RRFS_v1beta.xml (cherry-picked from PR https://github.com/NOAA-EMC/fv3atm/pull/173 for release/public-v2)

## Testing

For regression testing information, see https://github.com/ufs-community/ufs-weather-model/pull/184.

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/487
https://github.com/NOAA-EMC/fv3atm/pull/157
https://github.com/ufs-community/ufs-weather-model/pull/184

### CODE REVIEW

**Comment by grantfirl** [comment]
@climbfuji Would it be prudent to change https://github.com/NCAR/gmtb-scm/pull/188/files to mimic this PR? Also, the linked PR has changes to namelist values for GFS_v15p2 and GFS_v16beta and I don't see associated changes in FV3. Should those be reverted?

**Comment by climbfuji** [comment]
> @climbfuji Would it be prudent to change https://github.com/NCAR/gmtb-scm/pull/188/files to mimic this PR? Also, the linked PR has changes to namelist values for GFS_v15p2 and GFS_v16beta and I don't see associated changes in FV3. Should those be reverted?

Thanks @grantfirl. I was not aware of the namelist changes. I will need to try making those and see if the regression tests still pass. The linked PR is out of date or somehow messed up, it tries to remove several additions to `GFS_typedefs.F90` (and `GFS_typedefs.meta`?), for example most of the RRTMGP stuff.

**Comment by grantfirl** [comment]
> > @climbfuji Would it be prudent to change https://github.com/NCAR/gmtb-scm/pull/188/files to mimic this PR? Also, the linked PR has changes to namelist values for GFS_v15p2 and GFS_v16beta and I don't see associated changes in FV3. Should those be reverted?
> 
> Thanks @grantfirl. I was not aware of the namelist changes. I will need to try making those and see if the regression tests still pass. The linked PR is out of date or somehow messed up, it tries to remove several additions to `GFS_typedefs.F90` (and `GFS_typedefs.meta`?), for example most of the RRTMGP stuff.

Yes, I'm currently updating that PR so that it only has the new changes. I'm just not sure about the namelist changes on our supported suites. It seems like they would change results, but IDK.

**Comment by grantfirl** [comment]
I tried to merge in the latest master to the code in that PR without success (the manual merge produced something that was still incorrect). I'm going to just start from the current master and implement the changes in GFS_typedefs.[F90/meta] from this PR instead rather than trying to fix the existing PR, because it's just quicker/easier. The only question that remains for me is the namelist changes.

**Comment by mjiacono** [comment]
Let me know if I can help.  No namelist changes are necessary to run your baseline with the new cloud overlap code in place. If iovr=4 or 5 is activated (the new cloud overlap methods), then a new namelist parameter, idcor, is available to select the decorrelation method, but that’s not needed for iovr=1 (the default overlap).

**Comment by grantfirl** [comment]
@mjiacono Thanks for the information about namelist parameters. There is a new pull request for the SCM that has your changes (only): https://github.com/NCAR/gmtb-scm/pull/192. Please review it when you get a chance, and I'll close out the old one.

**Comment by climbfuji** [comment]
> Let me know if I can help. No namelist changes are necessary to run your baseline with the new cloud overlap code in place. If iovr=4 or 5 is activated (the new cloud overlap methods), then a new namelist parameter, idcor, is available to select the decorrelation method, but that’s not needed for iovr=1 (the default overlap). From: grantfirl <notifications@github.com> Reply-To: NOAA-EMC/fv3atm <reply@reply.github.com> Date: Tuesday, August 11, 2020 at 5:08 PM To: NOAA-EMC/fv3atm <fv3atm@noreply.github.com> Cc: "Iacono, Mike" <miacono@aer.com>, Mention <mention@noreply.github.com> Subject: Re: [NOAA-EMC/fv3atm] RRTMG cloud overlap method update (#157) I tried to merge in the latest master to the code in that PR without success (the manual merge produced something that was still incorrect). I'm going to just start from the current master and implement the changes in GFS_typedefs.[F90/meta] from this PR instead rather than trying to fix the existing PR, because it's just quicker/easier. The only question that remains for me is the namelist changes. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_NOAA-2DEMC_fv3atm_pull_157-23issuecomment-2D672280271&d=DwMCaQ&c=birp9sjcGzT9DCP3EIAtLA&r=z-5X-ef4F1rEw4zuUiN46A&m=QgYrLzrbVFqPSEsy4lDoxWX_884kRX-42ndDQV5EYgw&s=ersc8hjJIaAX9CKH1CSAGmCSfjE_gR32P_m63xQgKOw&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AE7W55DZOHRAEGX2W3Y65YDSAGXMPANCNFSM4P3P262A&d=DwMCaQ&c=birp9sjcGzT9DCP3EIAtLA&r=z-5X-ef4F1rEw4zuUiN46A&m=QgYrLzrbVFqPSEsy4lDoxWX_884kRX-42ndDQV5EYgw&s=ScG0TP62G2jWEUaGrD4hYVzRYHXRlZ3O1rxUiEZ0Ad0&e=>.
> […](#)

It turns out that I need to leave out the suggested namelist updates for the UFS, because all regression tests fail (different results) if I use them. So for now, need to keep
```
  isubc_sw     = 2
  isubc_lw     = 2
```
for ufs-weather-model's `parm/ccpp_v15p2_c96.nml.IN`, and
```
  iovr_lw      = 3
  iovr_sw      = 3
  isubc_sw     = 2
  isubc_lw     = 2
```
for ufs-weather-model's `parm/ccpp_v16beta_c96.nml.IN`.

**Comment by mjiacono** [comment]
Regarding isubclw/sw, this controls whether to use mcica for sub-grid clouds (isubc=1,2) or a simpler sub-grid cloud method (isub=0), so this setting will definitely change the results.  The new cloud overlap methods are only active for isubc=1,2, which selects the method for setting the random number seeds, though either can be used.  In my judgement, isubc=2 is the best choice for the global model.




________________________________

This email is intended solely for the recipient. It may contain privileged, proprietary or confidential information or material. If you are not the intended recipient, please delete this email and any attachments and notify the sender of the error.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA @junwang-noaa this PR is ready for review

**Review by llpcarson — APPROVED** [review]
looks good to me, approved

**Review by panll — APPROVED** [review]

**Comment by panll** [comment]
Looks good to me, approved.

**Review by junwang-noaa — APPROVED** [review]

**Comment by SMoorthi-emc** [comment]
I think I am the wrong reviewer for this commit as I do not have sufficient knowledge of the science behind it.  As QingFu Liu is the current radiation expert at EMC may be he should review this.  Otherwise, if the developer certifies that the changes are OK, then it is OK with me. I would like to comment on levr and levs being the  same in RRGMGP.  This would be problem if RRTMGP is applied to deep atmosphere (i.e. WAM)

**Comment by climbfuji** [comment]
> I think I am the wrong reviewer for this commit as I do not have sufficient knowledge of the science behind it. As QingFu Liu is the current radiation expert at EMC may be he should review this. Otherwise, if the developer certifies that the changes are OK, then it is OK with me. I would like to comment on levr and levs being the same in RRGMGP. This would be problem if RRTMGP is applied to deep atmosphere (i.e. WAM)

Thank you, Moorthi. Yes, Mike Iacono has seen the code changes and is ok with them. Regarding RRTMGP, you are correct, this will need to be changed if it is used in the deep atmosphere.

**Pull request merged**
