### PR TITLE
Add two way fire coupling to fv3atm

### LINKED ISSUE #814: Fire Coupling UFSATM <-> Community Fire Behavior Model
## Description
Add two-way coupling for the [community fire behavior model](https://ral.ucar.edu/model/community-fire-behavior-model). 

## Solution
This will include a new coupling flag `cpl_fire` which will be used to enable export of fields in the NUOPC cap. The model will also import new fields for coupling heat flux, upwards specific humidity, and smoke tracers into the physics.
- hflx_fire
- evap_fire
- smoke_fire

## Alternatives
(none)

## Testing:
1. The rt.conf test has been used and one test from each compile line has been executed on derecho.
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes? As noted above the ufs-weather-model tests have been executed. The baseline results have not changed but a new regression test has been added for coupling atm and fbh (fire behavior)

## Dependent PRs:
The ccpp physics package requires modifications to complete this issue.
https://github.com/ufs-community/ccpp-physics/pull/193

### PR DESCRIPTION
**Pull request by danrosen25**
## Description
This PR satisfies two-way coupling requirements for fv3atm and the [community fire behavior model](https://ral.ucar.edu/model/community-fire-behavior-model). It includes an option to enable fire coupling 'cpl_fire', which enables several export fields needed by the fire behavior model. It also includes new import fields for ccpp physics: heat flux from fire, upward specific humidity flux from fire, and smoke tracer. This is a draft PR until the ccpp physics coupling dependency is satisfied and the **submodule can be updated appropriately**.

Co-author: @masih-e

### Issue(s) addressed
- fixes #814

## Testing
The rt.conf test has been used and one test from each compile line has been executed on derecho with the intel compiler. The baseline results have not changed but a new regression test has been added for coupling atm and fbh (fire behavior). This test is here: [New Test](https://github.com/esmf-org/ufs-weather-model/blob/feature/ufs_fire_cpl/tests/rt.conf#L426)

## Dependencies
This dependency needs to be satisfied before the fv3atm changes can be complete
https://github.com/ufs-community/ccpp-physics/pull/193

### CODE REVIEW

**Comment by grantfirl** [comment]
@danrosen25 @masih-e Please review/merge https://github.com/esmf-org/fv3atm/pull/1. This updates this branch to work with the top of develop. This should be merged AFTER https://github.com/esmf-org/ccpp-physics/pull/1

**Comment by grantfirl** [comment]
After merging in the top of develop, we need to remove the draft status too.

**Comment by grantfirl** [comment]
@danrosen25 Thanks for merging. Please review and merge https://github.com/esmf-org/CMEPS/pull/1 next. And, please remember to remove the draft status on this PR in order to enter the UFS merge queue.

**Comment by danrosen25** [comment]
Done, and once the [PR for ccpp](https://github.com/ufs-community/ccpp-physics/pull/193) is complete we can update the branch location and mark this as ready. 
https://github.com/NOAA-EMC/fv3atm/pull/815/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584R11

**Comment by grantfirl** [comment]
> Done, and once the [PR for ccpp](https://github.com/ufs-community/ccpp-physics/pull/193) is complete we can update the branch location and mark this as ready. https://github.com/NOAA-EMC/fv3atm/pull/815/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584R11

We can't merge https://github.com/ufs-community/ccpp-physics/pull/193 and update .gitmodules here until UFS code managers have tested and approved the chain of PRs from fv3atm upwards, and they won't start the final testing/review process until this is out of draft mode.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by zach1221** [comment]
@jkbk2004 ccpp-physics PR [193](https://github.com/ufs-community/ccpp-physics/pull/193) is merged, and .gitmodule/hash updated. Please feel free to merge this fv3atm PR.

**Pull request merged**
