### PR TITLE
Fix RAP (Grell Freitas) decomp b4b issues

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
This replaces https://github.com/NOAA-EMC/fv3atm/pull/543, which is identical, but comes from another fork. All of this work comes from @climbfuji 

## Description
Update .gitmodules and submodule pointer for ccpp-physics for code review and testing of the changes described in https://github.com/NCAR/ccpp-physics/pull/933.

## Issue(s) addressed
See https://github.com/ufs-community/ufs-weather-model/pull/1243.

## Testing
See https://github.com/ufs-community/ufs-weather-model/pull/1243.

## Dependencies
waiting on https://github.com/NCAR/ccpp-physics/pull/933
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/194

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]
The GF code changes in ccpp-physics look like mine, I don't know anything about the moninshoc or dycore updates.

**Comment by DusanJovic-NOAA** [comment]
Please list dycore PR as a dependency.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
> Please list dycore PR as a dependency.

I just added it. The merge is waiting on that dependency now; the ccpp-physics PR is already merged.

**Comment by SamuelTrahanNOAA** [comment]
This PR is ready to be merged. The two PRs on which it depends have been merged, and the branch is updated to point to the head of the authoritative atmos_cubed_sphere and ccpp/physics branches.

**Comment by SamuelTrahanNOAA** [comment]
I'd like @jkbk2004 to confirm he's ready for code managers to merge this.

**Comment by jkbk2004** [comment]
Sure! we can merge in this PR.

**Pull request merged**
