### PR TITLE
Correction of convective cloud condensate in prog closure for HR2

### PR DESCRIPTION
**Pull request by lisa-bengtsson**
This PR updates the prognostic closure in samfdeepcnv.f and samfshalcnv.f for HR2:
1) correction (bug-fix) of convective cloud condensate passed to progsigma_calc.F90 routine
2) Update to only consider positive buoyant levels in integral (to make it general if a convection scheme can have negative buoyant levels between cloud base and cloud top)
3) Update to make the prognostic closure general to pass in q-tendency due to turbulence from any PBL scheme. 
4) Move out computation of q-tendency due to dynamics from progsigma_clac.F90 (to samfshalcnv and samfdeepcnv) because other convection schemes compute this term in a pre/post step. I will update samf* routines to use pre/post convection in the future.

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by Qingfu-Liu — APPROVED** [review]

**Comment by grantfirl** [comment]
@lisa-bengtsson https://github.com/ufs-community/ccpp-physics/pull/57 was merged. This is ready to revert the changes in .gitmodules (which it looks like you already did) and update the ccpp/physics submodule pointer to the latest commit (after the ccpp-physics PR was merged) in ufs/dev.

**Comment by jkbk2004** [comment]
@lisa-bengtsson ccpp pr was merged . can you update ccpp submodule pointer? correct hash is https://github.com/ufs-community/ccpp-physics/commit/57c444f6535bf34cbe8e75a52a74ea3bec2f8f50

**Comment by jkbk2004** [comment]
@lisa-bengtsson branch is pointing to ccpp 03acf73 hash. correct one is 57c444f

**Review by jkbk2004 — APPROVED** [review]

**Comment by lisa-bengtsson** [comment]
@jkbk2004 Now it looks to be correct. Thank you.

**Comment by lisa-bengtsson** [comment]
@jkbk2004 is this merged?

**Pull request merged**
