### PR TITLE
Fix out-of-bounds access in module_diag_hailcast.F90 which crashes RRFS on WCOSS2

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Description
Fixes a bug that can crash the RRFS ensembles. When KBAS=1, there's an out-of-bounds write in an array. That corrupts memory and occasionally crashes the model.

### Issue(s) addressed

FIXME: insert issue here.

#### How were these changes tested?  

Reran the failed case on Hera and WCOSS2 Dogwood. It passed. Also ran the regression tests on Hera.

#### What compilers / HPCs was it tested with?  

Intel WCOSS2, Intel Hera, GNU Hera.

#### Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  

Existing regression tests are sufficient.

#### Have the ufs-weather-model regression test been run? On what platform?  

Yes. Hera.

#### Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.

No.

#### Please commit the regression test log files in your ufs-weather-model branch

Done.

## Dependencies

- waiting on https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/308

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
This is a draft because I discovered I used the wrong fix. I need to do this instead:

```diff
-    DO k=KBAS,nz
+    DO k=KBAS+1,nz
        RWA_new(k) = RWA_new(k) / (h1d(k)-h1d(k-1))
     ENDDO
 ```

I'm testing this now on WCOSS2 and Hera.

**Comment by SamuelTrahanNOAA** [comment]
The correct fix works too. This is ready for review.

**Review by jkbk2004 — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA cubed sphere pr was merged

**Comment by SamuelTrahanNOAA** [comment]
I reverted .gitmodules and updated the atmos_cubed_sphere submodule hash to use dev/emc.

This PR is ready for final review and merge.

**Pull request merged**
