### PR TITLE
CCPP metadata bugfixes in GFS_typedefs.meta, update fv3 files with fms.2021.03, IAU bug fix for restart files

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR corrects a few wrong dimension names in `GFS_typedefs.meta`. These errors had no consequences in the past and as such, the code and model results are unchanged. There are also metadata bug fixes in the associated ccpp-physics PR.

Update 09/02: This PR now also contains the changes in https://github.com/NOAA-EMC/fv3atm/pull/380 from @junwang-noaa, see description there. #380 also contains a bug fix for writing out restart files correctly as required for IAU (see issue https://github.com/ufs-community/ufs-weather-model/issues/785).

Associated PRs:

https://github.com/NCAR/ccpp-physics/pull/722
https://github.com/NOAA-EMC/fv3atm/pull/379
https://github.com/ufs-community/ufs-weather-model/pull/782

For regression testing, see https://github.com/ufs-community/ufs-weather-model/pull/782

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@climbfuji would you please combine the fv3atm PR#380? It has two files update and there is no impact on results. Thanks

**Comment by climbfuji** [comment]
> @climbfuji would you please combine the fv3atm PR#380? It has two files update and there is no impact on results. Thanks

I can, but there are too many code changes in critical files (`atmos_model.F90` and `module_fcst_grid_comp.F90`) to merge it in without rerunning the regression tests in my opinion.

**Comment by junwang-noaa** [comment]
I ran some RT tests on dell. I will run full RT on hera today. I haven't
created ufs-weather-model PR yet.

**Comment by climbfuji** [comment]
> I ran some RT tests on dell. I will run full RT on hera today. I haven't created ufs-weather-model PR yet.
> […](#)

Ok, I can update the fv3atm PR, then we need to ask Rahul to update the submodule pointer in the ufs-weather-model PR, and then we rerun hera.gnu and hera.intel. Sounds ok?

**Comment by junwang-noaa** [comment]
Sorry, I am confused, will this PR be committed with Rahul's PR#781? I thought PR#781 links to fv3atm [PR#378](https://github.com/NOAA-EMC/fv3atm/pull/378). Your ufs-weather-model PR#782 will link to this fv3 PR.

**Comment by climbfuji** [comment]
> Sorry, I am confused, will this PR be committed with Rahul's PR#781? I thought PR#781 links to fv3atm [PR#378](https://github.com/NOAA-EMC/fv3atm/pull/378). Your ufs-weather-model PR#782 will link to this fv3 PR.

Oh I am sorry, not you but I am confused! Of course, no problem merging this into my PR. Has nothing to do with Rahul's PR. Time for a long weekend it seems ...

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
The ccpp-physics submodule pointer was updated, hash is correct. Ready to merge.

**Pull request merged**
