### PR TITLE
Bug fix for cloud effective radius for convective clouds (HR1)

### PR DESCRIPTION
**Pull request by ChunxiZhang-NOAA**
### Issue(s) addressed

- fixes #ufs-community/ccpp-physics<[#36](https://github.com/ufs-community/ccpp-physics/issues/36)>

## Dependencies

- waiting on ufs-community/ccpp-physics/pull/<[#35](https://github.com/ufs-community/ccpp-physics/pull/35)>

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by grantfirl** [comment]
@ChunxiZhang-NOAA The ccpp-physics PR has been merged and this is ready to update and merge.

**Review by jkbk2004 — APPROVED** [review]

**Comment by grantfirl** [comment]
Sorry for tagging Chunxi. I forgot that he is out today.

**Comment by jkbk2004** [comment]
Sure! I am merging in thi pr.

**Comment by BrianCurtis-NOAA** [comment]
> Sorry for tagging Chunxi. I forgot that he is out today.

No problem, he asked me to take care of the reverts and hash updates

**Pull request merged**
