### PR TITLE
Bug fix for ccpp-physics routine sfcsub.F

### LINKED ISSUE #199: sfcsub.F - bug in interpolation of GLDAS data
# Description

The model land mask passed to routine `fixrdc` is not correct for GLDAS data.

```
            else  ! the new gldas data.  it does not have data defined at landice
                  ! points.  so for efficiency, don't have fixrdc try to
                  ! find a value at landice points as defined by the vet type (vet).
              allocate(slmask_noice(len))
              slmask_noice=1.0
              do i = 1, len
                if (nint(vet(i)) < 1 .or.
     &              nint(vet(i)) == landice_cat) then
                  slmask_noice(i) = 0.0
                endif
              enddo
              .......
                call fixrdc(lugb,fnsmcc,kpdsmc,kpd7,mon,slmask_noice,
     &                      smc(1,k,nn),len,iret
     &,                     imsk, jmsk, slmskh, gaus,blno, blto
     &,                     outlat, outlon, me)
```

The GLDAS data should be interpolated to model points with some land, but excluding those land points identified as permanent land ice. This is done by checking each point's vegetation type (vet). Water points are screened out by checking if the vegetation category is a negative fill value. However, newer versions of the tiled vegetation type data have a non-negative water category at non-land points. As a result, `fixrdc` attempts to interpolate GLDAS data to water points. This bogs down the interpolation so that running a C768 case with UFS_UTILS program `global_cycle` can take over 15 minutes. Normally, a C768 case should run in under one minute using one MPI task per model tile.

## Steps to Reproduce

This bug was reported in https://github.com/NOAA-EMC/global-workflow/issues/2498

## The Fix

A simple fix has been tested - initialize "slmask_noice" to "slmskl".

```
               allocate(slmask_noice(len))
-              slmask_noice = 1.0
+!             slmask_noice = 1.0
+              slmask_noice = slmskl
```

UFS_UTILS regression tests for the global_cycle program all passed with this fix. So, the bug does not give bad results. Rather, it is computationally inefficient.

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## Description

No changes to fv3atm other than pointing to a new version of the ccpp physics to
address a bug in sfcsub.F routine.

### Issue(s) addressed

Fixes https://github.com/ufs-community/ccpp-physics/issues/199

## Testing

Full set of ufs-weather-model regression tests were run on Hera and passed.

## Dependencies

- https://github.com/ufs-community/ccpp-physics/pull/202
- https://github.com/ufs-community/ufs-weather-model/pull/2253

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
The title of this PR is "Test fix to ...". Is this just for testing the fix, or is this intended to be actually merged into develop branch? @GeorgeGayno-NOAA

**Comment by GeorgeGayno-NOAA** [comment]
> The title of this PR is "Test fix to ...". Is this just for testing the fix, or is this intended to be actually merged into develop branch? @GeorgeGayno-NOAA

According to the CCPP repository wiki page (see step 4), any changes to CCPP must also include PRs for FV3ATM and UFS weather model: 

https://github.com/ufs-community/ccpp-physics/wiki#instructions-for-ccpp-physics-code-developers

I did not make any changes to FV3ATM itself.

**Comment by DusanJovic-NOAA** [comment]
> > The title of this PR is "Test fix to ...". Is this just for testing the fix, or is this intended to be actually merged into develop branch? @GeorgeGayno-NOAA
> 
> According to the CCPP repository wiki page (see step 4), any changes to CCPP must also include PRs for FV3ATM and UFS weather model:
> 
> https://github.com/ufs-community/ccpp-physics/wiki#instructions-for-ccpp-physics-code-developers
> 
> I did not make any changes to FV3ATM itself.

I was actually asking about the title itself. The "Test fix to ..." implies that this is just for testing. But since this needs to be merged into fv3atm the title should be "Bug fix for ccpp-physics routine sfcsub.F" like the corresponding ufs PR.

**Comment by grantfirl** [comment]
@jkbk2004 @DusanJovic-NOAA This is combined into https://github.com/NOAA-EMC/fv3atm/pull/831 and therefore it can be closed.

**Pull request closed without merging**
