### PR TITLE
Add p8b SDF

### LINKED ISSUE #478: Add SDF for p8b coupled and standalone
## Description
Add SDF for p8b settings for coupled and uncoupled. 

## Solution
Add SDFs originally made by @yangfanglin  

Files are here: https://github.com/jessicameixner-noaa/fv3atm/tree/feature/p8b

## Testing:

1. Have you tested the code changes? On what platforms? In progress. 
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change? Yes 
- If yes, please give brief explanation of your code updates on the regression test.
The results will change because the tests will be updated to use these PRs.  

## Dependent PRs:

None

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Provide a detailed description of what this PR does.  
What bug does it fix, or what feature does it add?  
Is a change of answers expected from this PR?  

This PR adds SDF for the p8b settings which was created by @yangfanglin  and adds the corresponding coupled SDF for p8b.    

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #478 

## Testing

How were these changes tested?  with the ufs-weather-model regtests 
What compilers / HPCs was it tested with?  hera.intel orion.intel 
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  Yes, hera/orion 
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below. Yes, the coupled model tests all have setting changes
- Please commit the regression test log files in your ufs-weather-model branch (did not do this yet, will add soon)

## Dependencies

- waiting on PR https://github.com/NOAA-EMC/fv3atm/pull/489 to be merged first or combined with this PR.

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA I made a PR to your fv3atm branch to fix issue #488 without using the AdvanceCount from the ESMF_clockget call. There is no change to the model clock in the fv3_cap. I have asked Dusan and Raffaele to review the code changes. Thanks

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for letting me know.  Have the regression tests been run with your fix yet, or do I need to do that?

**Comment by junwang-noaa** [comment]
I have run several RT tests from your ufs-weather-model, but not all. I can run full RT on dell using the baseline you created after you merge the code.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa Just wanted to make sure and get the regtests started asap if you wanted me to run them.  I'll wait for word from  @DusanJovic-NOAA @rmontuoro and/or you as to when you are ready for the PR to be merged in.   Let me know if there's anything else I can do to help.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Both Dusan and Raffaele reviewed the code, please merge. 
Also we are committing Ted's physics PR, after that we will work on your PR#1071. Thanks

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by rmontuoro — COMMENTED** [review]
@junwang-noaa - please make sure this update includes your latest changes.

**Comment by junwang-noaa** [comment]
Thanks, Raffaele. @JessicaMeixner-NOAA Please merge the PR I made to your branch on the na name change. Thanks

**Comment by JessicaMeixner-NOAA** [comment]
@rmontuoro @junwang-noaa should be there now

**Review by rmontuoro — APPROVED** [review]
Thanks @JessicaMeixner-NOAA - looks good.

**Pull request merged**
