### PR TITLE
Doc update for public release (submodules ccpp-physics and ccpp-framework)

### PR DESCRIPTION
**Pull request by ligiabernardet**
Update .gitmodules and submodule pointers for ccpp-framework and ccpp-physics for code review and testing

### CODE REVIEW

**Comment by ligiabernardet** [comment]
Associated PRs
https://github.com/NCAR/ccpp-physics/pull/420
https://github.com/NCAR/ccpp-framework/pull/274

**Comment by climbfuji** [comment]
Hmm. This looks weird. I am seeing 21 files with changes for ccpp-physics, even though https://github.com/NCAR/ccpp-physics/pull/420 only changed 7 files. And I am seeing zero changes for ccpp-framework, even though https://github.com/NCAR/ccpp-framework/pull/274 changed 17 files.

**Comment by climbfuji** [comment]
The correct hashes should be: for ccpp-framework, 08763e93477ef9eaf7263ac0ec75c689df3c2c8f; for ccpp-physics, c385ad4ac957a8aab32fa8cfec5166cf8b198f63.

**Comment by ligiabernardet** [comment]
Yep, I am trying to figure out what went wrong.

**Comment by ligiabernardet** [comment]
Hashes look correct now.

**Comment by climbfuji** [comment]
I double-checked the submodule pointers, they are correct now. For reference, the correct hashes are:

ccpp-physics
```
commit c385ad4ac957a8aab32fa8cfec5166cf8b198f63 (HEAD, ncar/release/public-v4)
Merge: e0a32c4 fd0698c
Author: Dom Heinzeller <dom.heinzeller@icloud.com>
Date:   Tue Mar 31 15:57:41 2020 -0600

    Merge pull request #420 from mzhangw/scidoc_update

    SCI doc v4.0 updates
```
ccpp-framework
```
commit 08763e93477ef9eaf7263ac0ec75c689df3c2c8f (HEAD, ncar/release/public-v4)
Merge: 4197e92 9610038
Author: Dom Heinzeller <dom.heinzeller@icloud.com>
Date:   Tue Mar 31 15:58:09 2020 -0600

    Merge pull request #274 from JulieSchramm/release/public-v4

    Update CCPP variable pdf files for SCM v4.0 and UFS v1.0 release.
```

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA This PR is ready to merge as far as I am concerned.

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
