### PR TITLE
Update Regression Test to include gfsv17 prototypes that are after prototype 8, and turn on prognostic closure

### PR DESCRIPTION
**Pull request by lisa-bengtsson**
## Description

These PR’s in ufs-weather-model, fv3atm and ccpp/physics does the following:
Creates a set of _gfsv17 RT’s to reflect tests that are beyond prototype 8 targeted for GFSv17
Activates prognostic closure by setting namelist progsigma = true in *gfsv17 and pointing to new field_table in the RT’s
Addresses additional parametric tuning in progclosure_calc.F90
Adds a new gfsv17 field_table and diag_table

### Issue(s) addressed
https://github.com/ufs-community/ufs-weather-model/issues/1477

## Testing

New ufs-weather-model RT tests have been carried out on Hera

## Dependencies

https://github.com/ufs-community/ufs-weather-model/pull/1480
https://github.com/ufs-community/ccpp-physics/pull/18

### CODE REVIEW

**Comment by jkbk2004** [comment]
@lisa-bengtsson can you update ccpp submodule pointer and revert the gitmodules branch?

**Comment by lisa-bengtsson** [comment]
@jkbk2004 I updated the pointer in .gimodules

**Comment by jkbk2004** [comment]
@lisa-bengtsson correct ccpp hash is https://github.com/ufs-community/ccpp-physics/commit/befc3364d35172cc6133a5b0f883e9d2c0bac5a2. Can you update the ccpp submodule poiinter?

**Comment by lisa-bengtsson** [comment]
@jkbk2004 how can I see the submodule hashes ?

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
> @jkbk2004 how can I see the submodule hash
The ccpp hash on your branch  is pointing to correct one now. All looks fine to merge in here.

**Comment by lisa-bengtsson** [comment]
> > @jkbk2004 how can I see the submodule hash
> > The ccpp hash on your branch  is pointing to correct one now. All looks fine to merge in here.

Ok, thank you for confirming.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA @BrianCurtis-NOAA you can go ahead to approve this pr.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
