### PR TITLE
 Add WoFS suite definition file for SRW app

### PR DESCRIPTION
**Pull request by MicroTed**
## Description

Adds an SDF for SRW app v2 release for WoFS (Warn on Forecast System). It is the same as the RRFS_v1nssl SDF except for using Noah LSM instead of Noahmp. This SDF is planned for use in the 2022 Spring Forecast Experiment. It will also be used for an option in the regional workflow.

## Testing

Works the same as RRFS_v1nssl except for namelist changes to use lsm=1 (and iems=1, ialb=1)

Regression tests would be needed only if we want to change the rrfs_v1nssl test to instead use the wofs_v0 suite. Since the main reason is to check the microphysics option, it's not clear any change there is needed, unless we also remove the rrfs_v1nssl suite.

## Dependencies

Needed by PR  for regional workflow. https://github.com/ufs-community/regional_workflow/pull/708 
 @ywangwof

### CODE REVIEW

**Comment by JeffBeck-NOAA** [comment]
@MicroTed @ywangwof, there was a request at the UFS code managers meeting this morning to create a new RT using this SDF.  This will ensure b4b reproducibility moving forward.  It could be run on one of the 3-km sub-CONUS or coarser CONUS domains using the SRW App/FV3-LAM, and doesn't need to be a long forecast.  Thanks!

**Comment by grantfirl** [comment]
@MicroTed As others have noted, great job on quickly getting to the bottom of the ORT failures -- impressive. Once you've updated your branch in https://github.com/NCAR/ccpp-physics/pull/904, please update this PR branch as you would other nested PRs:

- checkout your updated PR branch of ccpp/physics
- cd up to FV3
- `git add ccpp/physics`
- edit .gitmodules to point to your ccpp/physics PR fork and branch
- `git add .gitmodules`
- git commit
- git push

**Comment by MicroTed** [comment]
> * cd up to FV3

@grantfirl  Will do! Should it be the current develop branch of fv3atm, or a particular commit? I did the CCPP at a not-the-latest commit level because the most recent had broken something in fv3atm that I didn't feel like figuring out... 

The restart problem was an easy fix. The dcp was more subtle, and hampered by my adding new bugs, haha

**Comment by grantfirl** [comment]
> > * cd up to FV3
> 
> @grantfirl Will do! Should it be the current develop branch of fv3atm, or a particular commit? I did the CCPP at a not-the-latest commit level because the most recent had broken something in fv3atm that I didn't feel like figuring out...
> 
> The restart problem was an easy fix. The dcp was more subtle, and hampered by my adding new bugs, haha

You should be in your PR ([add-wofs-suite](https://github.com/MicroTed/fv3atm/tree/add-wofs-suite)) branch for all of this, but your PR branches should also have the latest main/develop branches merged into them. That is, for any code that is being considered for merging, it has to be that latest code + your PR changes only.

**Comment by grantfirl** [comment]
@MicroTed Just be sure to merge in the latest main branch of ccpp-physics into [nssl_restart_ccn](https://github.com/MicroTed/ccpp-physics/tree/nssl_restart_ccn) before you do this though since ccpp-physics is the submodule.

**Comment by MicroTed** [comment]
@grantfirl I am having the worst day with git... I *think* I have things updated, but it seems the wrong ccpp/physics directory is loading.

**Comment by grantfirl** [comment]
> @grantfirl I am having the worst day with git... I _think_ I have things updated, but it seems the wrong ccpp/physics directory is loading.

No problem. It looks like fv3atm is pointing to the right ccpp-physics commit and ufs-weather-model is pointing to the latest commit in your branch, but it looks to me like there may have been one step missing, which is my fault for not putting it in the instructions. I think that we still need to merge in the latest develop branch into your fv3atm [add-wofs-suite](https://github.com/MicroTed/fv3atm/tree/add-wofs-suite) branch since it looks like it's missing some recent commits. 

Here's how I would fix this, although there are probably a bunch of other equally valid methods. In your local FV3 directory, check out the develop branch.

- `git checkout develop`

Pull down the latest commits from the authoritative repo, assuming that is called origin on your local machine:

- `git pull origin develop`

This should pull down some changes. Now, checkout your PR branch again and merge in develop again.

- `git checkout add-wofs-suite`
- `git merge develop`
- `git push -u YOUR_FV3ATM_GITHUB_FORK`

Once this is done, you'll need to update the fv3atm submodule pointer one more time in your ufs-weather-model branch. Keeping FV3 as-is, with your newly updated PR branch still checked out, cd up to ufs-weather-model. Edit .gitmodules so that the branch for FV3 says add-wofs-suite. It currently still says 'develop'. Now, the following:

-  `git add .gitmodules`
- `git add FV3`
- `git commit -m 'edit .gitmodules and update FV3 submodule pointer'`
- `git push -u YOUR_UFS_WEATHER_MODEL_FORK`

**Comment by MicroTed** [comment]
@grantfirl I thought I had updated my fv3atm to the latest develop, but I’ll check later when I get back home.

**Comment by junwang-noaa** [comment]
@MicroTed It looks to me that your ufs-weather-model branch has not been synced with the latest develop branch yet, please check. Thanks.

**Comment by grantfirl** [comment]
@MicroTed Since we merged https://github.com/NCAR/ccpp-physics/pull/904 separately, this PR branch can now point to the main branch of ccpp-physics. Please revert the changes to .gitmodules, checkout the latest ccpp-physics main branch, cd up to FV3, `git add ccpp/physics`, git commit, and git push.

**Comment by MicroTed** [comment]
> Please revert the changes to .gitmodules, checkout the latest ccpp-physics main branch, cd up to FV3, `git add ccpp/physics`, git commit, and git push

@grantfirl done (I think) and then merged to current develop branch (hope that worked correctly)

**Comment by DusanJovic-NOAA** [comment]
@MicroTed What is the status of this PR?

**Comment by MicroTed** [comment]
> @MicroTed What is the status of this PR?

@DusanJovic-NOAA  The SRW app added the suite in a separate branch. My understanding is that folks want to wait to add it to the main branch until the regional restart reproducibility issue is resolved. (Restarts with the regional option do not provide bit-for-bit results.)

**Comment by DusanJovic-NOAA** [comment]
@ChunxiZhang-NOAA Can we close this PR?

**Comment by ChunxiZhang-NOAA** [comment]
@DusanJovic-NOAA Sure, please close this PR.

**Pull request closed without merging**
