### PR TITLE
MYNNsfc uniform real kind

### PR DESCRIPTION
**Pull request by dustinswales**
## Description

This change modifies REAL-type variables and specific REAL-type constants so that they uniformly utilize the kind=kind_phys definition for REAL types found in the CCPP-physics machine.F file. This reduces casting and recasting of REALs between types of differing precision. Additional changes include changing occurances of ALOG to LOG to support more than single precision REALs as needed when kind=kind_phys is defined in that manner.
Opened on behalf of @timsliwinski-noaa 

## Testing
No changes to baselines for UFS regression tests with Intel on Cheyenne.

### CODE REVIEW

**Comment by grantfirl** [comment]
@dustinswales Reminder to point to https://github.com/NCAR/ccpp-framework/pull/456

**Comment by dustinswales** [comment]
> @dustinswales Reminder to point to [NCAR/ccpp-framework#456](https://github.com/NCAR/ccpp-framework/pull/456)

@grantfirl Thanks for the reminder. Done.

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 The ccpp-physics PR was merged.  It needs to wait for this ccpp-framework [PR](https://github.com/NCAR/ccpp-framework/pull/456) being merged.

**Comment by jkbk2004** [comment]
@dustinswales can you update ccpp-framework and ccpp submodule pointers and revert gitmodules branchs?

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
