### PR TITLE
release/public-v1: update ccpp-physics (fix unicode errors)

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

For a description of the problem and how it is solved, see https://github.com/NCAR/ccpp-physics/pull/499. This PR only updates the submodule pointer for ccpp-physics.

Note that we will need to retag fv3atm v1.1.0 after this PR is merged.

## Testing

See https://github.com/ufs-community/ufs-weather-model/pull/204

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/499
https://github.com/NOAA-EMC/fv3atm/pull/172
https://github.com/ufs-community/ufs-weather-model/pull/204

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
@junwang-noaa ready to merge!

**Comment by climbfuji** [comment]
Thanks, @junwang-noaa - can you please retag fv3atm as ufs-v1.1.0?
```
commit c3e10fc0374197b3a7533ff13c02367dd2ade6b7 (HEAD, noaa-emc/release/public-v1)
Author: Dom Heinzeller <dom.heinzeller@icloud.com>
Date:   Mon Sep 21 14:43:57 2020 -0600

    release/public-v1: update ccpp-physics (fix unicode errors) (#172)

    * Update .gitmodules and submodule pointer for ccpp-physics
    * Revert change to .gitmodules and update submodule pointer for ccpp-physics
```

**Comment by junwang-noaa** [comment]
Done.

**Comment by climbfuji** [comment]
I don't see the tag yet, unfortunately. Do you need to push it to GitHub?

**Comment by junwang-noaa** [comment]
I did, can you refresh the github page and check it again?

**Comment by climbfuji** [comment]
This is what I have:
```
heinzeller-lt:FV3 dom.heinzeller$ git remote update
Fetching noaa-emc
Fetching dom
Fetching ncar
Fetching noaa-gsd
heinzeller-lt:FV3 dom.heinzeller$ git remote -v show
dom	https://github.com/climbfuji/fv3atm (fetch)
dom	https://github.com/climbfuji/fv3atm (push)
ncar	https://github.com/NCAR/fv3atm (fetch)
ncar	https://github.com/NCAR/fv3atm (push)
noaa-emc	https://github.com/NOAA-EMC/fv3atm (fetch)
noaa-emc	https://github.com/NOAA-EMC/fv3atm (push)
noaa-gsd	https://github.com/NOAA-GSD/fv3atm (fetch)
noaa-gsd	https://github.com/NOAA-GSD/fv3atm (push)
```
and:
```
commit c3e10fc0374197b3a7533ff13c02367dd2ade6b7 (HEAD, noaa-emc/release/public-v1)
Author: Dom Heinzeller <dom.heinzeller@icloud.com>
Date:   Mon Sep 21 14:43:57 2020 -0600

    release/public-v1: update ccpp-physics (fix unicode errors) (#172)

    * Update .gitmodules and submodule pointer for ccpp-physics
    * Revert change to .gitmodules and update submodule pointer for ccpp-physics

commit 8457028350c29a914c4130851767e6adbe731bfc (tag: ufs-v1.1.0)
Author: Dom Heinzeller <dom.heinzeller@icloud.com>
Date:   Fri Sep 4 14:02:01 2020 -0600

    Update submodule pointer for GFDL_atmos_cubed_sphere (#167)

    Update the submodule pointer to point to the head of branch ufs-release/public-v1 of GFDL_atmos_cubed_sphere. This version of the dycore is identical to tag ufs-v1.0.0 except for minor documentation updates (inline documentation).
```

**Comment by junwang-noaa** [comment]
Please see:
https://github.com/NOAA-EMC/fv3atm/tree/ufs-v1.1.0

I deleted previous tag ufs-v1.1.0 and made a new tag ufs-v1.1.0 from the
latest release/public-v1 branch.

**Comment by climbfuji** [comment]
> Please see: https://github.com/NOAA-EMC/fv3atm/tree/ufs-v1.1.0 I deleted previous tag ufs-v1.1.0 and made a new tag ufs-v1.1.0 from the latest release/public-v1 branch.
> […](#)

I see. Strange, don't understand why I don't get it locally. In any case, all good!

**Pull request merged**
