### PR TITLE
Wrapper PR for #261, #271, #268: zorl interstitial, ocn -> wat, merra2 threading

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR combines the changes in #261, #271, #268. For details about each of these PRs, please see there. The individual PRs have been approved by the appropriate physics developers, if necessary.

## Testing

See https://github.com/ufs-community/ufs-weather-model/pull/520.

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/623
https://github.com/NOAA-EMC/fv3atm/pull/279
https://github.com/ufs-community/ufs-weather-model/pull/520

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA This PR is ready to merge anytime, but if you want to wait for the last jet.intel regression tests to finish, then please do so. I had to resubmit again on jet due to slurm timeouts, sent a message to the jet help team to look at these ongoing problems.

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA Finally the jet regression tests finished and this PR can be merged.

**Comment by junwang-noaa** [comment]
Merged.

**Comment by climbfuji** [comment]
> Merged.
> […](#)

Thanks!

**Pull request merged**
