### PR TITLE
bug fixed for mraerosol

### PR DESCRIPTION
**Pull request by AnningCheng-NOAA**
## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Provide a detailed description of what this PR does.  
What bug does it fix, or what feature does it add?  
A bug fixed for MERRA2 coupled Thompson microphysics. The cloud water number concentration was not passed back when calling the microphysics, resulting model crash for some hurricane cases.
Is a change of answers expected from this PR?  
Yes. Baseline changed whenever mraerosol=T: merra2_thompson and atmaero_control_p8_rad_micro

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #<1914>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested?  
RTs in hera
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Yes
Have the ufs-weather-model regression test been run? On what platform?  
Yes. at Hera: /scratch1/NCEPDEV/global/Anning.Cheng/ufs-weather-model/tests
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- yes. /scratch1/NCEPDEV/global/Anning.Cheng/ufs-weather-model/tests
- Please commit the regression test log files in your ufs-weather-model branch
- commited

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by zach1221** [comment]
@AnningCheng-NOAA sub-component PR ccpp-physics [#109](https://github.com/ufs-community/ccpp-physics/pull/109) has been merged.  Can you please update the submodule pointer (ccpp-physics hash: 69c9764f3ad33ec94ecc5c45891ad9745da5c569) and revert the url change in .gitmodules?

**Comment by grantfirl** [comment]
@AnningCheng-NOAA https://github.com/ufs-community/ccpp-physics/pull/109 was merged. Please update the ccpp/physics submodule pointer to the latest commit on the ufs/dev branch and revert the changes to .gitmodules in preparation for merge.

**Comment by grantfirl** [comment]
@AnningCheng-NOAA .gitmodules should have:
`[submodule "ccpp/physics"]`
`path = ccpp/physics`
`url = https://github.com/ufs-community/ccpp-physics`
`branch = ufs/dev`

**Comment by grantfirl** [comment]
@AnningCheng-NOAA Also, the ccpp-physics submodule hash isn't correct. Like @zach1221 said, it should be ccpp-physics hash: 69c9764f3ad33ec94ecc5c45891ad9745da5c569

If you cd into ccpp/physics, just checkout the latest ufs/dev branch from https://github.com/ufs-community/ccpp-physics and it should be the correct one. You keep on pulling in the main branch from the NCAR fork, which is not what the develop branch of fv3atm should be pointing to.

**Comment by grantfirl** [comment]
@AnningCheng-NOAA Also, the ccpp-framework hash should be https://github.com/NCAR/ccpp-framework/tree/1b6352fb24f053b738bde72eed0ddf0b60ec7c0f. Please don't pull in the latest main since it will cause a failure in one of the RTs.

**Comment by AnningCheng-NOAA** [comment]
Grant, I just pushed in   69c9764f3ad33ec94ecc5c45891ad9745da5c569. Is it
correct now?

**Comment by grantfirl** [comment]
Yes, ccpp/physics is correct, but ccpp-framework needs to be reverted. And, is the UPP hash supposed to be updated here? I thought this was only supposed to be the small ccpp-physics change?

**Comment by grantfirl** [comment]
OK, looks good now. I see that https://github.com/ufs-community/ufs-weather-model/pull/1915 says that UPP is supposed to be updated in here. I think we're good now.

**Comment by AnningCheng-NOAA** [comment]
Grant, I think upp change is minor and it is already in.

**Comment by zach1221** [comment]
Thanks, @AnningCheng-NOAA and @grantfirl for the assistance.

@jkbk2004 @BrianCurtis-NOAA review notifications have been sent out, please review this PR when you're able.

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by zach1221** [comment]
@jkbk2004 can you merge as well, please sir?

**Pull request merged**
