### PR TITLE
reduce memory required by MERRA2 data

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

Updates ccpp/physics with to reduce memory required by ingested MERRA2 data. This allows the coupled model at C384 mx025 resolution to run on Cheyenne.intel with the default resources. Answers in the P7 regression tests are B4B with this change if the ``diag_table`` in the current tests is not changed.

### Issue(s) addressed

- fixes ufs-weather-model issue [#698](https://github.com/ufs-community/ufs-weather-model/issues/698)

## Testing

See ufs-weather-model PR [#866](https://github.com/ufs-community/ufs-weather-model/pull/866) for testing. 

Baselines change for ufs-weather-model only because of update to the ``diag_table`` used by the P7 coupled and standalone tests. 

Bot the ``cpld_control_c384_p7`` and ``cpld_bmark_p7`` tests run successfully on Cheyenne.intel with this change.

## Dependencies

-  NCAR/ccpp [#757](https://github.com/NCAR/ccpp-physics/pull/757)
- Required for ufs-weather-model PR [#866](https://github.com/ufs-community/ufs-weather-model/pull/866)

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@DeniseWorthen Thanks for making the code changes. Can you check how much memory are reduced by this change?

**Review by junwang-noaa — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@junwang-noaa I can't really find  an obvious signal in the memory usage if I turn on the ``profile_memory`` option for the coupled c384 test

**Comment by AnningCheng-NOAA** [comment]
approved the pull request

**Comment by climbfuji** [comment]
Merged as part of https://github.com/NOAA-EMC/fv3atm/pull/398, close?

**Comment by DeniseWorthen** [comment]
Closed. Code was merged as part of #398

**Pull request closed without merging**
