### PR TITLE
Add no_nsst CCPP suites

### PR DESCRIPTION
**Pull request by climbfuji**
Based on #67, but use different names (no_nsst instead of no_NST).

Associated PR: https://github.com/ufs-community/ufs-weather-model/pull/61 - see there for testing.

### CODE REVIEW

**Comment by climbfuji** [comment]
I believe it is safe to merge this PR already (but not yet the ufs-weather-model). But we can also wait until all tests are completed.

**Comment by junwang-noaa** [comment]
> I believe it is safe to merge this PR already (but not yet the ufs-weather-model). But we can also wait until all tests are completed.

I believe so, but let's get these suite files tested before we commit them.

**Comment by climbfuji** [comment]
I need to create a new baseline on hera first and ask you to move it. Will take a bit. Cheyenne+GNU is running.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
All tests pass, this PR is ready to merge.

**Review by junwang-noaa — APPROVED** [review]

**Comment by junwang-noaa** [comment]
Dom,

This pull request is merged, you can update the submodule in
ufs-weather-model pull requests. Thanks a lot for adding these two no nsst
tests.

Jun

**Comment by climbfuji** [comment]
Done, please go ahead and merge this PR - thanks, Jun!

**Pull request merged**
