### PR TITLE
Add a new SDF named FV3_WoFS_v0 for SRW_v2.1 release

### PR DESCRIPTION
**Pull request by ChunxiZhang-NOAA**
## Description
This PR includes two main tasks: 
1) In favor of [PR#514](https://github.com/NOAA-EMC/fv3atm/pull/514).  All credit for code changes and description to @MicroTed.  It adds an SDF for SRW app v2.1 release for WoFS (Warn on Forecast System). It is the same as the RRFS_v1nssl SDF except for using Noah LSM instead of NoahMP. This SDF was planned for use in the 2022 Spring Forecast Experiment. It will also be used for an option in the regional workflow.
2)  CCPP Scientific Documentation updates for UFS-SRW v2.1.0 [#14](https://github.com/ufs-community/ccpp-physics/pull/14). Note that it includes a minor bug fix to include variable nf_albd in the host model (CCPP_typedefs). 

## Testing
The description of the regression test is provided in the ufs-weather-model level PR[#1460](https://github.com/ufs-community/ufs-weather-model/pull/1460).

## Dependencies
waiting on ufs-community/ccpp-physics/pull/[#14](https://github.com/ufs-community/ccpp-physics/pull/14)

### CODE REVIEW

**Comment by ligiabernardet** [comment]
@ChunxiZhang-NOAA Thank you for this PR. Should a regression test be added so we can make sure this publicly released and supported suite does not break going forward?

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA Thank you for this PR. Should a regression test be added so we can make sure this publicly released and supported suite does not break going forward?

@ligiabernardet Yes, the regression test is added [here](https://github.com/ufs-community/ufs-weather-model/pull/1460).

**Comment by ChunxiZhang-NOAA** [comment]
@MicroTed Could you please review this PR.

**Comment by grantfirl** [comment]
@ChunxiZhang-NOAA As soon as you point the ccpp/physics pointer to https://github.com/ufs-community/ccpp-physics/pull/14 in this PR, I'll get rid of the drafts in fv3atm/ufs-weather-model that I created for the docs update.

**Comment by ChunxiZhang-NOAA** [comment]
@MicroTed  I noticed that GFS_suite_interstitial_4 is not in suite_FV3_RRFS_v1nssl.xml and suite_FV3_WoFS_v0.xml. There is part of code for "imp_physics == imp_physics_nssl" in GFS_suite_interstitial_4.F90. Do you know why it is not included in the suite definition file?

**Comment by grantfirl** [comment]
> @MicroTed I noticed that GFS_suite_interstitial_4 is not in suite_FV3_RRFS_v1nssl.xml and suite_FV3_WoFS_v0.xml. There is part of code for "imp_physics == imp_physics_nssl" in GFS_suite_interstitial_4.F90. Do you know why it is not included in the suite definition file?

@ChunxiZhang-NOAA It is not needed. I asked @MicroTed the same question and here was his response (copied from email): "GFS_suite_interstitial_4 only does something specifically for NSSL-2mom if there are droplets or ice crystals injected by a **convection parameterization**. (Creates number concentration for the new particles.)"

Since there is no convection in this suite, there is no reason to call this interstitial in the WoFS suite.

**Comment by MicroTed** [comment]
Yes, thanks for chiming in, @grantfirl -- If there is no parameterized convection, then the interstitial subroutines do nothing.

**Comment by ChunxiZhang-NOAA** [comment]
@grantfirl @MicroTed Thank you!

**Comment by ChunxiZhang-NOAA** [comment]
@grantfirl I pointed the ccpp-physics pointer to Man's branch. Saw you have closed those draft PRs, haha.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA @RatkoVasic-NOAA all tests are done on [ufs-wm pr 1460](https://github.com/ufs-community/ufs-weather-model/pull/1460). This pr can be merged once @ChunxiZhang-NOAA revert gitmodules.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 @DusanJovic-NOAA @RatkoVasic-NOAA Done.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
