### PR TITLE
NRL Neptune model 32-bit physics support

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Description

Adds ccpp-physics changes needed to support 32-bit physics on Neptune. This does *not* add 32-bit physics to FV3, which requires quite a lot more changes in several repositories.

### Issue(s) addressed

Implements what this PR was supposed to:

https://github.com/NCAR/ccpp-physics/pull/797

Which is about half of this batch of changes from NRL:

https://github.com/NCAR/ccpp-physics/pull/772

## Testing

Original testing was done on Neptune model by NRL. After that, it was tested in UFS, with these changes disabled. Finally, another set of branches (not in this PR) were developed that can successfully compile UFS for 32-bit physics, but not yet run it that way.

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/918

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
As of this posting, this PR is up-to-date with all submodules and has passed intel compiler tests (on jet) and gnu compiler tests (on hera).

**Comment by SamuelTrahanNOAA** [comment]
I have changed the `.gitmodules` from ssh to https due to permission problems.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
@SamuelTrahanNOAA Please update .gitmodules and ccpp/physics hash ([f13ed4e](https://github.com/NCAR/ccpp-physics/commit/f13ed4e8018859ec4e0aa5da3f36328b826d8b1f)

**Comment by SamuelTrahanNOAA** [comment]
This branch now points to the NCAR main branch of ccpp/physics.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
