### PR TITLE
Remove cheyenne.pgi from CCPP config

### PR DESCRIPTION
**Pull request by climbfuji**
This PR:
- remove `cheyenne.pgi` from CCPP config (`ccpp/set_compilers.sh`, `ccpp/build_ccpp.sh`)

Associated PRs:
https://github.com/NCAR/ccpp-framework/pull/295
https://github.com/NOAA-EMC/fv3atm/pull/117
https://github.com/NOAA-EMC/NEMS/pull/63
https://github.com/ufs-community/ufs-weather-model/pull/139

For regression testing information, see below https://github.com/ufs-community/ufs-weather-model/pull/139.

### CODE REVIEW

**Comment by climbfuji** [comment]
Note: I flagged this PR and associated PRs as "ready to merge" in case these make it to the top of the commit queue during my two days of holidays. Please do not merge unless agreed upon with @DusanJovic-NOAA and @junwang-noaa.

**Comment by climbfuji** [comment]
@junwang-noaa do you know why the changes related to tiice are still showing up in my PR? I thought this was merged last week?

Attached is a screenshot of the diffs between develop as of today (left), and my code (right). I don't see any of those differences that GitHub is talking about. All clean.


Screen Shot 2020-06-01 at 3 08 00 PM

**Review by junwang-noaa — COMMENTED** [review]
I am confused, why  the code changes in PR #119 are here?

**Comment by climbfuji** [comment]
Ok, fixed now. I think this was because I had pulled in Shan's changes before they got merged, but the merge was a squashed-merge and GitHub got confused. I did a `git rebase` and removed her commit, then pulled in develop again. The code is exactly the same before/after (I kept a copy of the FV3 directory to make sure), thus no need to rerun the tests, and now we only see the three changes we expect.

Screen Shot 2020-06-01 at 3 14 12 PM

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
