### PR TITLE
Inline post Updates

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
This PR is for: 

- updating upp submodule hash from the UPP repository
- updating inline post interface with reading some new variables required by SFS
- passing LSM number 'landsfcmdl' from model to upp

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #[2477](https://github.com/ufs-community/ufs-weather-model/issues/2477)

## Testing

How were these changes tested?  
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

# Requirements before merging
- [ ] All new code in this PR is tested by at least one unit test
- [ ] All new code in this PR includes Doxygen documentation
- [ ] All new code in this PR does not add new compilation warnings (check CI output)

### CODE REVIEW

**Review by jkbk2004 — APPROVED** [review]
pre-test ran ok on weather model side.

**Comment by BrianCurtis-NOAA** [comment]
Is there a UPP PR associated with this, or just bumping the hash to an already merged UPP?

**Comment by jkbk2004** [comment]
> Is there a UPP PR associated with this, or just bumping the hash to an already merged UPP?

@BrianCurtis-NOAA UPP develop branch continues to be updated with PRs tested and merged. This PR is intended to catch up latest commit: https://github.com/NOAA-EMC/UPP/commit/ce5f3b146861cf6c95e1c14c640ede1ed97e6eef.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
Testing for [2489](https://github.com/ufs-community/ufs-weather-model/pull/2489) has completed, please continue with the merge process, thank you.

**Pull request merged**
