### PR TITLE
pressure is not density and weasdi is not snodi + #739 and #742

### LINKED ISSUE #737: GFS_diagnostics output "snodi" is actually weasdi
## Description

In GFS_Diagnostics.F90, the snodi diagnostics is actually weasdi:

```f90
ExtDiag(idx)%name = 'snodi'
ExtDiag(idx)%desc = 'water equivalent snow depth over ice'
...
    ExtDiag(idx)%data(nb)%var2 => sfcprop(nb)%weasdi(:)
```

It should be snodi instead:

```f90
ExtDiag(idx)%name = 'snodi'
ExtDiag(idx)%desc = 'snow depth over ice'
    ExtDiag(idx)%data(nb)%var2 => sfcprop(nb)%snodi(:)
```

### To Reproduce:
N/A

## Additional context
N/A

## Output
N/A

### LINKED ISSUE #741: crash when running GFS PBL/sfclay and clm lake in RRFS ensemble
## Description
A couple of RRFS ensemble members crashed with GFS PBL (TKE-EDMF)/sfclay and clm lake combined. This happened when lake water was frozen to lake ice in clm lake.

The reason for the crash is because clm lake is called between surface layer scheme and PBL scheme. If there is a state change in clm lake, particularly water turning into ice, stability related variables over ice will be missing and cause the crash.
Please see the attached slides for more information.

[clm_lake_bug_fix.pptx](https://github.com/NOAA-EMC/fv3atm/files/13715823/clm_lake_bug_fix.pptx)

### To Reproduce:
1. perform a forecast with GFS PBL/sfclayer combined with clm lake
2. wait for lake water turning into lake ice, which could happen in winter time further north
3. model crashed with AVOST error message from RUC LSM

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
      AVOST IN VILKA     Table index=  -2147483648

 I,J=           1           1 LU_index =           17 Psfc[hPa] =

                     NaN Tsfc =    262.537014420372
```

## Testing:

1. Have you tested the code changes? On what platforms?
Yes. On Hera.
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
Yes.
- Will the baseline results change? 
No.
- If the baseline results change, is it expected? Please give brief explanation.

## Dependent PRs:

https://github.com/ufs-community/ccpp-physics/pull/148

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Description

***PRs #739 and #742 are combined into this one***

Fixes two bugs:

1. CLM Lake was using near-surface pressure in place of near-surface density.
2. GFS_diagnostics was outputting weasdi (water equivalent snow depth over ice) in place of snodi (snow depth over ice)

Fixes are from @tanyasmirnova 

### Issue(s) addressed

- fixes https://github.com/NOAA-EMC/fv3atm/issues/737

These PRs are included in this one. They can be closed when this PR is merged:
- closes #739 
- closes #742

Due to #742:
- fixes #741

Many ccpp-physics issues are closed, and two pull requests. For a full list, see https://github.com/ufs-community/ccpp-physics/pull/139

#### How were these changes tested?  

A failing RRFS test case.

#### What compilers / HPCs was it tested with?  

Intel Hera

#### Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  

Existing tests already exercise this code well. Sadly, no test can catch every possible failure.

#### Have the ufs-weather-model regression test been run? On what platform?  

Hera.

#### Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.

All tests with "hrrr" or "clm_lake" in their name.

/scratch1/BMC/zrtrr/Samuel.Trahan/lakes/RT/NEMSfv3gfs/develop-20231207

#### Please commit the regression test log files in your ufs-weather-model branch

Done.

## Dependencies

- waiting on https://github.com/ufs-community/ccpp-physics/pull/139

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
Since you are touching GFS_diagnostics.F90 can you please fix the typo in the description of wilting point 'wilt':

https://github.com/NOAA-EMC/fv3atm/blob/a82381c0b751a15e5343de5078ef836b2c444c89/ccpp/driver/GFS_diagnostics.F90#L2181

**Comment by SamuelTrahanNOAA** [comment]
> Since you are touching GFS_diagnostics.F90 can you please fix the typo in the description of wilting point 'wilt':
> 
> https://github.com/NOAA-EMC/fv3atm/blob/a82381c0b751a15e5343de5078ef836b2c444c89/ccpp/driver/GFS_diagnostics.F90#L2181

Will that change the results of any test?

Changing snodi affects nothing since no test outputs snodi.

**Comment by DusanJovic-NOAA** [comment]
> > Since you are touching GFS_diagnostics.F90 can you please fix the typo in the description of wilting point 'wilt':
> > https://github.com/NOAA-EMC/fv3atm/blob/a82381c0b751a15e5343de5078ef836b2c444c89/ccpp/driver/GFS_diagnostics.F90#L2181
> 
> Will that change the results of any test?
> 
> Changing snodi affects nothing since no test outputs snodi.

I noticed the typo by looking at ncdump, so yes it will change the output, but I have no idea how many tests are affected. Ignore it, since this PR does not change outputs.

**Review by tanyasmirnova — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
@JiliDong-NOAA - Please confirm that I merged your changes into this branch correctly.

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA - Please confirm that I merged your changes into this branch correctly.

looks good too.

**Review by jkbk2004 — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA physics pr was merged.

**Comment by SamuelTrahanNOAA** [comment]
This PR is ready for final review and merge. I reverted .gitmodules and pointed ccpp/physics to ufs-community's ufs/dev.

**Pull request merged**
