### PR TITLE
fix grv function used by NST

### LINKED ISSUE #130: grv function used by NST assumes wrong argument
# Description

The NST model uses the function ``grv`` to give the latitude dependence of gravity. 

https://github.com/ufs-community/ccpp-physics/blob/c2ec9e5e165dac07a991424bd22bb0667cf32017/physics/module_nst_water_prop.f90#L485-L500

This function assumes the argument is the latitude but the value actually used by ``sfc_nst.f`` is the sin(latitude).

https://github.com/ufs-community/ccpp-physics/blob/c2ec9e5e165dac07a991424bd22bb0667cf32017/physics/sfc_nst.f#L372

## Additional Context

See [gravity forumla 1980](http://www-gpsg.mit.edu/~tah/12.221_2005/grs80_corr.pdf) for the definition of gravity=f(latitude) used in this module.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

Changes argument used by ``grv`` function.

### Issue(s) addressed

- fixes https://github.com/ufs-community/ccpp-physics/issues/130

## Testing

- changes almost all UWM baselines. Logs will be posted in ufs-community/ufs-weather-model/pull/2001

## Dependencies

- depends on https://github.com/ufs-community/ccpp-physics/pull/131

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by DusanJovic-NOAA** [comment]
Can this PR be combined with #719?

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA Since this changes so many baselines, I'd prefer to have it go alone. The other PR is not breaking anything but I want to make a few more changes.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Since this changes so many baselines, I'd prefer to have it go alone. The other PR is not breaking anything but I want to make a few more changes.

OK. Thanks. I should have looked at corresponding UFSWM PRs to see that one PR changes baselines and other doesn't.

**Comment by zach1221** [comment]
@jkbk2004 we have approval here and are ready to merge.

**Pull request merged**
