### PR TITLE
Update GEFS branch to current production

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
When I ported the GEFS production branch over to GitHub, some later commits were missed. This PR brings it back in line with the actual GEFS model version.

### CODE REVIEW

**Comment by XianwuXue-NOAA** [comment]
Walter, you have Bring GEFS v12 production branch up-to-date (#205) which included all the commit, do you want to overwrite the commit?

**Comment by WalterKolczynski-NOAA** [comment]
> Walter, you have Bring GEFS v12 production branch up-to-date (#205) which included all the commit, do you want to overwrite the commit?

Apparently I missed some. I'm not sure how, as they were sitting in the same branch in my repo.

**Comment by bingfu-NOAA** [comment]
@WalterKolczynski-NOAA   I didn't see which commit you missed, can you point it out?

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA I didn't see which commit you missed, can you point it out?

If you go to the commits tab of the PR, it lists all the commits that are being added

**Comment by bingfu-NOAA** [comment]
@WalterKolczynski-NOAA I saw 12 commits in your PR #333, but your PR #205 already included those 12 commits.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA I saw 12 commits in your PR #333, but your PR #205 already included those 12 commits.

Yeah, I don't know what happened. But if you check the current tip of production/GEFS_v12, it does not have these commits.

**Comment by bingfu-NOAA** [comment]
@WalterKolczynski-NOAA I get it. It looks like those commits do not show up from git log, though the codes already been updated. Do you want to revert PR #205 and merge this PR #333?

**Comment by XianwuXue-NOAA** [comment]
I checked the production/GEFS_v12 in EMC account (https://github.com/NOAA-EMC/fv3atm/commit/845eca4a13e6ab0ded5700f58cf5f44f2a9e29c0), it did include all these changes. However, this PR still show these changes. I don't know why? Maybe because your branch didn't synchronize with the EMC account?

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA I get it. It looks like those commits do not show up from git log, though the codes already been updated. Do you want to revert PR #205 and merge this PR #333?

This PR should fix the issue, there is no reason to worry about reverting #205.

**Comment by WalterKolczynski-NOAA** [comment]
> I checked the production/GEFS_v12 in EMC account ([845eca4](https://github.com/NOAA-EMC/fv3atm/commit/845eca4a13e6ab0ded5700f58cf5f44f2a9e29c0)), it did include all these changes. However, this PR still show these changes. I don't know why? Maybe because your branch didn't synchronize with the EMC account?

I don't think it's that either. At this point I don't really care what happened, I just want to fix it and move on.

**Review by bingfu-NOAA — APPROVED** [review]

**Review by XianwuXue-NOAA — APPROVED** [review]

**Pull request merged**
