### PR TITLE
create 'global_latlon' output_grid option

### PR DESCRIPTION
**Pull request by jswhit2**
This pull request implements a 'global_latlon' option for history file output.  
It works for 'netcdf' and 'netcdf_parallel' output.
If jmo is even, the regular lat/lon grid does not include the poles or equator.
If jmo is odd, the poles and equator is included.

Addresses issue #91

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Are there any tests for this code?

**Comment by jswhit2** [comment]
> Are there any tests for this code?

Not yet.

**Comment by climbfuji** [comment]
This capability will be very useful. The TC trackers require the input in lat-lon format, currently we have to use an additional regridding step from the gaussian grid to a lat-lon grib using wgrib2 before running the tracker (and interpolating twice doesn't improve the accuracy).

**Comment by junwang-noaa** [comment]
Code was committed in [#104](https://github.com/NOAA-EMC/fv3atm/pull/104), close PR.

**Pull request closed without merging**
