### PR TITLE
Update upp submodule

### LINKED ISSUE #809: Update upp submodule
## Description
The UPP develop branch has multiple updates:

- Transition modulefiles on Hera and Jet to Rocky
- GFS HR4 support

## Solution
Update revision of upp submodule to the latest one from the UPP repository.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Testing:

1. Have you tested the code changes? On what platforms?
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change?
- If yes, please give brief explanation of your code updates on the regression test.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<pr_number>
- associated ufs-weather-model/pull/<pr_number>

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
## Description

This PR is for updating upp submodule with recent changes from UPP repository which include Rocky8 transition on Hera and GFS HR4 support.
What bug does it fix, or what feature does it add?  
Is a change of answers expected from this PR?  

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #809

## Testing

How were these changes tested?  
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by DusanJovic-NOAA** [comment]
@WenMeng-NOAA Could you merge #805 into this PR? PR #805 modifies only one file (.github/workflows/GCC.yml).

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA Could you merge #805 into this PR? PR #805 modifies only one file (.github/workflows/GCC.yml).

@DusanJovic-NOAA Merged in my FV3 branch upp_HR4

**Comment by DusanJovic-NOAA** [comment]
> > @WenMeng-NOAA Could you merge #805 into this PR? PR #805 modifies only one file (.github/workflows/GCC.yml).
> 
> @DusanJovic-NOAA Merged in my FV3 branch upp_HR4

Thanks.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by zach1221** [comment]
@jkbk2004 we have approvals and are ready to merge here.

**Pull request merged**
