### PR TITLE
[Production/RRFS.v1] MYNN PBL, Smoke and subgrid cloud fraction updates RRFS.v1

### PR DESCRIPTION
**Pull request by haiqinli**
## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Provide a detailed description of what this PR does. 
-- Update the MYNN PBL, Smoke and subgrid cloud fraction for the RRFS.v1 code freeze. 

What bug does it fix, or what feature does it add? 
-- Merge the bugfix in the HAILCAST diagnostic code (unit issue) (https://github.com/NOAA-EMC/fv3atm/issues/320)
-- Merge   (https://github.com/NOAA-EMC/fv3atm/issues/801)

Is a change of answers expected from this PR?  Yes.

## Testing

How were these changes tested?  The changes were tested with retro runs and regression test.

What compilers / HPCs was it tested with?  Intel compiler on Hera and Jet.

Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  Yes.

Have the ufs-weather-model regression test been run? On what platform?  Yes, on Hera.
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
   Yes, because the physics changed.
- Please commit the regression test log files in your ufs-weather-model branch
   Yes, the regression test log file was committed.

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/ufs-community/ccpp-physics/pull/180
- waiting on [noaa-emc/fv3atm/pull/<pr_number>](https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/87)

### CODE REVIEW

**Comment by grantfirl** [comment]
@haiqinli This looks like #801 has been combined successfully.

**Comment by haiqinli** [comment]
@grantfirl Yes, https://github.com/NOAA-EMC/fv3atm/pull/801 has been combined.

**Comment by jkbk2004** [comment]
@haiqinli physics and cubed sphere PRs were merged. can you update hash and revert change in gitmodules?

**Comment by haiqinli** [comment]
@jkbk2004 The gitmodules have been reverted. Thanks.

**Comment by jkbk2004** [comment]
@haiqinli correct hashes are https://github.com/ufs-community/ccpp-physics/commit/85fabc0ae0762b938a30b4f1926009869297a108  and https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/commit/fab198c5815d707a8e8421e553d199eff945ffa9  can you cehck one more time?

**Comment by haiqinli** [comment]
@jkbk2004 Updates for the correct hashes of [ufs-community/ccpp-physics@85fabc0](https://github.com/ufs-community/ccpp-physics/commit/85fabc0ae0762b938a30b4f1926009869297a108) and [NOAA-EMC/GFDL_atmos_cubed_sphere@fab198c](https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/commit/fab198c5815d707a8e8421e553d199eff945ffa9) are done. Thanks.

**Comment by jkbk2004** [comment]
looks good! @MatthewPyle-NOAA this pr can be merged: with concise squash/merge commit message.

**Pull request merged**
