### PR TITLE
NCAR/main PR #66 (Bugfix and optimization of prognostic closure for the P8 physics suite)

### PR DESCRIPTION
**Pull request by dustinswales**
## Description

This PR is equivalent to [NCAR/fv3atm PR #66](https://github.com/NCAR/fv3atm/pull/66).

@lisa-bengtsson

### CODE REVIEW

**Comment by jkbk2004** [comment]
@dustinswales can you check @dustinswales fv3atm fork branch? It seems forked out of ncar-main fv3atm.

**Comment by jkbk2004** [comment]
> @dustinswales can you check @dustinswales fv3atm fork branch? It seems forked out of ncar-main fv3atm.

@DusanJovic-NOAA can you check @dustinswales fv3atm fork branch? It seems forked out of ncar-main fv3atm.

**Comment by DusanJovic-NOAA** [comment]
> > @dustinswales can you check @dustinswales fv3atm fork branch? It seems forked out of ncar-main fv3atm.
> 
> @DusanJovic-NOAA can you check @dustinswales fv3atm fork branch? It seems forked out of ncar-main fv3atm.

Correct. It's a fork of NCAR/fv3atm. It should be fork of NOAA-EMC/fv3atm.

**Comment by dustinswales** [comment]
@jkbk2004 The branch in this PR is [up-to-date](https://github.com/dustinswales/fv3atm/commits/ncar-main-PR967) with NOAA-EMC/fv3atm:develop.

**Comment by dustinswales** [comment]
> > > @dustinswales can you check @dustinswales fv3atm fork branch? It seems forked out of ncar-main fv3atm.
> > 
> > 
> > @DusanJovic-NOAA can you check @dustinswales fv3atm fork branch? It seems forked out of ncar-main fv3atm.
> 
> Correct. It's a fork of NCAR/fv3atm. It should be fork of NOAA-EMC/fv3atm.

@jkbk2004 @DusanJovic-NOAA Sorry, I'm not following the fork discussion here?

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 @DusanJovic-NOAA Is it mandatory to fork from NOAA-EMC/fv3atm?

**Comment by DusanJovic-NOAA** [comment]
> > > > @dustinswales can you check @dustinswales fv3atm fork branch? It seems forked out of ncar-main fv3atm.
> > > 
> > > 
> > > @DusanJovic-NOAA can you check @dustinswales fv3atm fork branch? It seems forked out of ncar-main fv3atm.
> > 
> > 
> > Correct. It's a fork of NCAR/fv3atm. It should be fork of NOAA-EMC/fv3atm.
> 
> @jkbk2004 @DusanJovic-NOAA Sorry, I'm not following the fork discussion here?

@jkbk2004 In this case the branch Dustin opened a pull request from is indeed up to date with develop. So it can be merged.

**Comment by jkbk2004** [comment]
I think technical ok for this PR since only one baseline change and all others pass. But to make a life easy for merging on fv3atm side, would that be easier to recreate another PR with update ccpp hash? Otherwise, sync issue of ncar main and emc develop.

**Comment by dustinswales** [comment]
> @jkbk2004 @DusanJovic-NOAA Is it mandatory to fork from NOAA-EMC/fv3atm?

@ChunxiZhang-NOAA @jkbk2004 @DusanJovic-NOAA 
It doesn't matter, from a git perspective, what fork is used by the developer for a PR. The only thing that is important is that the code in PR is up-to-date.

**Comment by DusanJovic-NOAA** [comment]
> @jkbk2004 @DusanJovic-NOAA Is it mandatory to fork from NOAA-EMC/fv3atm?

It is not. It is just easier to confirm that a branch is up to date with develop if it's in a fork from NOAA-EMC/fv3atm, no need to look at the commit history to verify that, which can be not very obvious if there are a lot of commits.

**Comment by ChunxiZhang-NOAA** [comment]
> > @jkbk2004 @DusanJovic-NOAA Is it mandatory to fork from NOAA-EMC/fv3atm?
> 
> It is not. It is just easier to confirm that a branch is up to date with develop if it's in a fork from NOAA-EMC/fv3atm, no need to look at the commit history to verify that, which can be not very obvious if there are a lot of commits.

I see. Thanks!

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Pull request merged**
