### PR TITLE
Fix aux2d dim

### PR DESCRIPTION
**Pull request by drnimbusrain**
## Description
There is a bug in dimension definition for the 2D auxiliary array.

This can only be identified if a user only wants to output 2D auxilarly arrays, and will face CCPP prebuild errors that clearly show the inconsistency.
```
    raise Exception('Dimension {}, required by variable {}, not defined in host model metadata'.format(
Exception: Dimension number_of_3d_auxiliary_arrays, required by variable auxiliary_2d_arrays, not defined in host model metadata
```

This bug also exists in the CCPP auxiliary ReadTheDocs:

https://ccpp-techdoc.readthedocs.io/en/latest/ParamSpecificOutput.html#output-of-auxiliary-arrays-from-ccpp
image

## Issue(s) addressed

#834 

## Testing

How were these changes tested?  
RDHPCs Hera.
No changes to baseline and regression tests not performed.

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
I do not see corresponding ufs-weather-model PR.

**Comment by drnimbusrain** [comment]
> I do not see corresponding ufs-weather-model PR.

@DusanJovic-NOAA Where in the ufs-weather-model are corresponding changes needed for this bug fix?  This is only a change for bugfix to fv3atm/ccpp/data/GFS_typedefs.meta.

**Comment by DusanJovic-NOAA** [comment]
The ufs-weather-model PR is required to run regression tests. Or, if you want I can merge this change into one of my PRs.

**Comment by drnimbusrain** [comment]
Ah, just updating the FV3 submodule hash in ufs-weather-model.

Yes, could you just merge it?  Thanks!

**Comment by DusanJovic-NOAA** [comment]
> Ah, just updating the FV3 submodule hash in ufs-weather-model. Yes, could you just merge it? Thanks!

Merged with #856

**Comment by DusanJovic-NOAA** [comment]
Merged via #856

**Pull request closed without merging**
