### PR TITLE
[production/RRFS.v1] Add clear-sky shortwave downward at surface flux to available diagnostics.

### PR DESCRIPTION
**Pull request by dustinswales**
## Description
This PR adds a new diagnostic, instantaneous downward shortwave flux at the surface assuming clear-sky conditions.
This is needed for RRFSv1.

Analogous to #824 into develop branch.

### Issue(s) addressed
N/A

## Testing
Tested on Hera using Intel compilers.
No change to results.

### CODE REVIEW

**Comment by MatthewPyle-NOAA** [comment]
@dustinswales @EricJames-NOAA  Are PRs coming for ccpp-physics and UFS WM to complete this one?

**Comment by EricJames-NOAA** [comment]
@MatthewPyle-NOAA can you see these?

https://github.com/ufs-community/ufs-weather-model/pull/2249
https://github.com/ufs-community/ccpp-physics/pull/198

**Comment by MatthewPyle-NOAA** [comment]
Yes, @EricJames-NOAA  - thanks.  Just modified the titles to add the [production/RRFS.v1]

**Comment by grantfirl** [comment]
@dustinswales @MatthewPyle-NOAA https://github.com/ufs-community/ccpp-physics/pull/198 is merged. This is ready to revert .gitmodules and update the ccpp-physics submodule pointer.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Looks good to me...approving

**Pull request merged**
