### PR TITLE
update GF for RRFS 2023 HWT SFE

### PR DESCRIPTION
**Pull request by haiqinli**
## Description

1). A update of the Grell-Freitas (GF) convection for RRFS;
2). A update of RUC LSM to use BNU soil property for RRFS;
3). A SDF of FV3_HRRR_gf will be used as a member of RRFS 2023 HWT SFE
4). This is an urgent PR for RRFS 2023 HWT SFE, which will start on May 1st, 2023;

## Testing

Have the ufs-weather-model regression test been run? On what platform?  
   Yes, on Hera with Intel and GNU compilers.
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
  Yes, there are changes for GF and soil property for RUC LSM. The new baseline directories are:
   (1). Hera/Intel: /scratch1/BMC/gsd-fv3-dev/NCEPDEV/stmp4/Haiqin.Li/Haiqin.Li/FV3_RT/rt_198134
   (2). Hera/GNU: /scratch1/BMC/gsd-fv3-dev/NCEPDEV/stmp4/Haiqin.Li/Haiqin.Li/FV3_RT/rt_71833
- Please commit the regression test log files in your ufs-weather-model branch
   Yes, the log files were committed to my ufs-weather-model branch.

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Review by Qingfu-Liu — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by grantfirl** [comment]
@haiqinli https://github.com/ufs-community/ccpp-physics/pull/64 was merged. Please revert your changes to the .gitmodules file and point to the latest commit of the ufs/dev branch of ccpp-physics (https://github.com/ufs-community/ccpp-physics/commit/494356c90724cc020c8b6e7e4089767324c4b215)

**Comment by jkbk2004** [comment]
@haiqinli ccpp pr was merged. can you update hash and revert change in gitmodules? correct hash is https://github.com/ufs-community/ccpp-physics/commit/494356c90724cc020c8b6e7e4089767324c4b215

**Comment by haiqinli** [comment]
@grantfirl @jkbk2004 Should I update gitmodules in both fav3atm and ufs-weather-model?

**Comment by grantfirl** [comment]
> @grantfirl @jkbk2004 Should I update gitmodules in both fav3atm and ufs-weather-model?

Just fv3atm right now. Once the fv3atm PR is merged, you'll do the same thing for ufs-weather-model.

**Comment by grantfirl** [comment]
@haiqinli It looks like this isn't pointing to the latest ccpp-physics commit yet. You'll need to do the following:

1. cd into your ccpp/physics
2. git checkout ufs/dev
3. git pull
4. Verify that the commit of ccpp/physics that you now have is https://github.com/ufs-community/ccpp-physics/commit/494356c90724cc020c8b6e7e4089767324c4b215
5. cd back into the FV3 directory
6. git add ccpp/physics
7. git commit -m "update ccpp/physics submodule pointer"
8. git push

**Pull request merged**
