### PR TITLE
Consistent names in the meta files

### PR DESCRIPTION
**Pull request by ShanSunNOAA**
Changing standard/long names to be consistent with variable names. No changes in output.

It corresponds to ccpp PR #456.

### CODE REVIEW

**Comment by climbfuji** [comment]
This PR needs to be updated with the latest code in fv3atm develop.

**Comment by ShanSunNOAA** [comment]
Hi Dom,

I thought I did that, but must have done something wrong.

When I do 'git difftool 9868550c6573c0fc2a35a5e0090ac7bea8121251
134c419507b2c73c94a5c2312fca517e655a977a", which are the latest in fv3atm
develop and my fork, respectively, only these two files differ:

gfsphysics/GFS_layer/GFS_typedefs.F90
gfsphysics/GFS_layer/GFS_typedefs.meta

Could you be more specific? Thanks,

Shan

**Comment by climbfuji** [comment]
The commit history shows all the commits from the previous PR, only the new commit(s) should show up: af6d943acd884b8f9fe465b0e170278fde8a4efb and following commits on May 27.

**Comment by ShanSunNOAA** [comment]
Got it. ".gitmodules" now points to a newly created ccpp branch. How do I refresh it? Thanks!

**Comment by ShanSunNOAA** [comment]
I will open a new PR. Thanks.

**Comment by ShanSunNOAA** [comment]
Hi Dom,

Thanks for your help. I think I fixed it now. How does it look to you?

Shan

**Pull request closed without merging**
