### PR TITLE
Add extended diagnostic output from Thompson MP, includes "Add optional scaling to RRTMGP flux adjustment" (#319), bug fix in several suite definition files

### LINKED ISSUE #338: Several suite definition files missing calls to GFS_radiation_surface
## Description

The following four suite definition files that are missing the call to `GFS_radiation_surface`:
```
suite_FV3_GFS_v15_thompson_mynn_RRTMGP.xml
suite_FV3_GFS_v16_coupled_noahmp.xml
suite_FV3_GFS_v16_coupled_nsstNoahmp.xml
suite_FV3_RRFS_v1alpha.xml
```

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR adds a set of dedicated 3d arrays for extended diagnostic output from Thompon MP, and a logical flag that controls allocating, outputting and resetting these arrays. This work is based on @ericaligo-NOAA 's code changes.

The flag to reset the extended diagnostics from Thompson MP is - for the UFS - currently tied to `avg_max_length`, which is used to reset maximum hourly fields (the corresponding reset variable is renamed to make its purpose clear).

This PR includes the changes in #319, "Add optional scaling to RRTMGP flux adjustment".

*Important* This PR fixes bugs in several suite definition files that were missing the call to `GFS_radiation_surface`:
```
suite_FV3_GFS_v15_thompson_mynn_RRTMGP.xml
suite_FV3_GFS_v16_coupled_noahmp.xml
suite_FV3_GFS_v16_coupled_nsstNoahmp.xml
suite_FV3_RRFS_v1alpha.xml
```

### Issue(s) addressed

Fixes https://github.com/NCAR/ccpp-physics/issues/680.
Fixes https://github.com/NOAA-EMC/fv3atm/issues/338.

## Testing

See https://github.com/ufs-community/ufs-weather-model/pull/658

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/679
https://github.com/NOAA-EMC/fv3atm/pull/331
https://github.com/ufs-community/ufs-weather-model/pull/658

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Review by ericaligo-NOAA — CHANGES_REQUESTED** [review]
Do you think the resetting or emptying of diagnostics should be controlled by a namelist parameter that has units of seconds (avg_max_length) since output less than 1 hour could often be used when diagnosing model/physics issues.  Currently, the resetting is controlled by fhzero, which, from my understanding is limited to hourly.

**Comment by climbfuji** [comment]
> Do you think the resetting or emptying of diagnostics should be controlled by a namelist parameter that has units of seconds (avg_max_length) since output less than 1 hour could often be used when diagnosing model/physics issues. Currently, the resetting is controlled by fhzero, which, from my understanding is limited to hourly.

I am actually not sure we should do that at all, because these arrays can be used in radiation or in physics, and for multiple purposes. Maybe we just tell developers who are using the `aux2d/3d` arrays that they need to take care of the resetting themselves, depending on their needs. Different story for the Thompson 3d diagnostics, though. Would you like to reset them in `avg_max_length` intervals instead?

**Comment by ericaligo-NOAA** [comment]
Oh yes, I was only referring to the 3D Thompson diagnostics.  That would be ideal to have them reset using the avg_max_length.

**Comment by climbfuji** [comment]
Submodule pointer for ccpp-physics has been updated, this PR is ready to merge. Sorry for the delay.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
