### PR TITLE
32-bit physics with FV3_RAP

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
This adds support for 32-bit physics to the FV3, based on prior work on the Neptune model. The 64-bit physics should not change results. Presently, the 32-bit physics are incompatible with MOM6 because it has conflicting stochastic_physics precision requirements, so MOM6-coupled configurations must use 64-bit physics.

## Issues

https://github.com/ufs-community/ufs-weather-model/issues/1288

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/930
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/193
~~https://github.com/earth-system-radiation/rte-rrtmgp/pull/180~~ this was already merged

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@SamuelTrahanNOAA For the overloading capability, would you like to try the Fortran polymorphic class? Please see example: 

https://github.com/NOAA-GFDL/FMS/pull/962/files#diff-e76bad5442df93e413ddc44d0e23dd628f667843a955bb471d5ff5ea036cd944

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA For the overloading capability, would you like to try the Fortran polymorphic class? Please see example:
> 
> https://github.com/NOAA-GFDL/FMS/pull/962/files#diff-e76bad5442df93e413ddc44d0e23dd628f667843a955bb471d5ff5ea036cd944

I think the resulting code would be just as complex, and would use features many developers don't know. If Fortran had templates or generics, I would use that, but it doesn't.

**Comment by SamuelTrahanNOAA** [comment]
> > @SamuelTrahanNOAA For the overloading capability, would you like to try the Fortran polymorphic class? Please see example:
> > https://github.com/NOAA-GFDL/FMS/pull/962/files#diff-e76bad5442df93e413ddc44d0e23dd628f667843a955bb471d5ff5ea036cd944
> 
> I think the resulting code would be just as complex, and would use features many developers don't know. If Fortran had templates or generics, I would use that, but it doesn't.

I see no obvious "best way" of cleaning up this code, so I made an issue here:

https://github.com/NOAA-EMC/fv3atm/issues/559

We can discuss a better option in that issue.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA so its this pr's turn to update and merge.

**Comment by SamuelTrahanNOAA** [comment]
The atmos_cubed_sphere and ccpp/physics point to the authoritative branches now. This PR is ready for final review and merge.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
I need a second review before this can be merged.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
