### PR TITLE
Revert calculation of T2m in NOAH-MP 

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
## Description

This reverts the calculation of T2m in NOAH-MP as it was found in p8c that it tends to result in overly low t2min and overly high t2max values.

### Issue(s) addressed

- https://github.com/ufs-community/ufs-weather-model/issues/1350

## Testing

How were these changes tested?   (In progress with ufs-weather-model regression testing) 
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline?  Yes, because t2m will change.  There will also be answer changes do to parameter setting updates for stability and improving aerosols. 

## Dependencies

- waiting on  https://github.com/NCAR/ccpp-physics/pull/948

### CODE REVIEW

**Comment by grantfirl** [comment]
https://github.com/NCAR/ccpp-physics/pull/948 has been merged. This is ready to update .gitmodules and the ccpp-physics submodule pointer in preparation for merge.

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA ccpp pr was merged. we can work here.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 I've updated the ccpp/physics module

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA Yeah, can you revert branch pointer in .gitmodules?

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 done.  Sorry my first push failed so I had to re-do it.

**Review by BrianCurtis-NOAA — APPROVED** [review]
Hash's look OK

**Pull request merged**
