### PR TITLE
release/public-v1: Python 3 compatibility for CCPP prebuild scripts

### PR DESCRIPTION
**Pull request by climbfuji**
This PR only updates the submodule pointer for ccpp-framework (and temporarily .gitmodules for code review and testing) for the changes described in https://github.com/NCAR/ccpp-framework/pull/271/files.

Associated PRs:
https://github.com/NCAR/ccpp-framework/pull/271/files
https://github.com/NOAA-EMC/fv3atm/pull/88
https://github.com/ufs-community/ufs-weather-model/pull/92

For regression testing information, see https://github.com/ufs-community/ufs-weather-model/pull/92

### CODE REVIEW

**Comment by climbfuji** [comment]
The ccpp-physics PR has been approved - once I have the green light from @DusanJovic-NOAA and @junwang-noaa I will merge it and update the submodule pointer in fv3atm.

**Review by junwang-noaa — APPROVED** [review]

**Comment by junwang-noaa** [comment]
I assume the python3 feature is tested, so it's OK to commit.

**Comment by climbfuji** [comment]
Yes, I tested running ccpp_prebuild.py manually with both Python 2.7 and Python 3.7 after making the changes. I tested the CCPP dynamic and CCPP static build options, both with `--debug` and without. They all worked and the auto-generated code from Python 3.7 was identical to that from Python 2.7. Will start the merge process now. Thanks!

**Comment by climbfuji** [comment]
Ok, this is ready to merge.

**Pull request merged**
