### PR TITLE
Update develop from NOAA-GSL: RUC ice, MYNN sfclay, stochastic land perturbations

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR contains changes required for the updates to ccpp-physics:
- addition of RUC ICE (replaces sfc_sice when RUC LSM is used): additional variables for RUC LSM, cleanup old/unused variables
- land surface perturbations (requires moving the initialization of the stochastic physics to after reading the initial/restart data)
- remove unused **tracer_sanitizer** scheme
- bugfixes in `GFS_typedefs.F90` that caused model crashes with GNU (trying to reset `Diag%cldcov` even though it was no longer allocated)
- add logic to apply land surface perturbations at every time step (as in WRF) or at `fhcyc` hours (as for GFS)

## Testing

For testing, see https://github.com/ufs-community/ufs-weather-model/pull/386

## Dependencies

https://github.com/noaa-psd/stochastic_physics/pull/36
https://github.com/NCAR/ccpp-physics/pull/558
https://github.com/NOAA-EMC/fv3atm/pull/239
https://github.com/ufs-community/ufs-weather-model/pull/386

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by ClaraDraper-NOAA — APPROVED** [review]

**Comment by junwang-noaa** [comment]
I am curious, I see sfc_sice is removed from the GSD suite files, so RUC has its own ice model for lake and ocean ice?

**Comment by tanyasmirnova** [comment]
@junwang-noaa Yes, the RUC LSM has now its own ice model and up-to-3-layer snow model for snow accumulated on sea/lake ice. The snow model computes snow fraction on ice as it is done over land. The RUC ice component has been used in the operational RAP and HRRR for several years.
The RUC ice model is applied only in the uncoupled FV3 model and can work with the fractional grid. RUC ice model implements a similar approach as in sfc_sice.f for the fractional sea-ice  cover.

**Comment by junwang-noaa** [comment]
@Thanks for the explanation. Actually fractional grid is my next question,
we are planning to add the fractional grid for standalone fv3 tests, we can
run standalone fv3 tests on fractional grid tests with sfc_sice. Are
additional changes required for the GSD_v0 test to run on the fractional
grid?

**Comment by tanyasmirnova** [comment]
@junwang-noaa The GSD_v0 does not need additional changes for the fractional grid.

**Comment by climbfuji** [comment]
> @junwang-noaa The GSD_v0 does not need additional changes for the fractional grid.

That's my understanding, too, but I haven't tested it myself.

**Comment by junwang-noaa** [comment]
Great, thanks

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
@junwang-noaa I think we can merge this. Clara already approved it for NOAA-PSL, and I haven't heard from Phil whether he has time to review it or not (but he approved the corresponding stochastic_physics changes yesterday).

**Review by pjpegion — COMMENTED** [review]
Looks good to me

**Pull request merged**
