### PR TITLE
Update inline post

### LINKED ISSUE #645: The in-line post interface clean up
## Description
Dusan suggests that the in-line post interface needs a clean up for legacy setting and code format.  

## Solution

>  I'm looking at the code I thought I should mention, there are many OMP directives in which im is listed as shared variable but it is not used in the code at all, for example
> 
> !$omp parallel do default(none) private(i,j) shared(jsta,jend,im,spval,pt,pd,pint,ista,iend)
>       do j=jsta,jend
>         do i=ista,iend
>           pd(i,j)     = spval
>           pint(i,j,1) = pt
>         end do
>       end do
> Also, code indentation is terrible, it is very difficult to reason about the code and understand the logic with inconsistent indentation. This file (post_fv3.F90) requires some serious clean up.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Testing:

1. Have you tested the code changes? On what platforms?
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change?
- If yes, please give brief explanation of your code updates on the regression test.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<pr_number>
- associated ufs-weather-model/pull/<pr_number>

### LINKED ISSUE #1748: Inline post: move computation of diagnostic variables outside a do loop that loads arrays from a bundle
In inline post the computation of diagnostic variables here:

https://github.com/NOAA-EMC/fv3atm/blob/160b422dc1d294623cc8ebfabfbe7d28d7c65c62/io/post_fv3.F90#L4353

from line 4353 to 4413 (and several other loops) should me moved outside of the field loop (after file_loop_all loop) . Those additional fields should be computed when all the fields from the fields bundle have been assigned values, otherwise these fields will be computed when each field is assigned values.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
This PR include changes are:

- Clean up legacy code in inline post interface
- Relocate computation of diagnostic variables
- Sync changes from offline post interface
- Update upp revision 

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #645
- fixes [ufs-weather-model/issues/1748
](https://github.com/ufs-community/ufs-weather-model/issues/1748)

## Testing

How were these changes tested?  
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
No.

Do PRs in upstream repositories need to be merged first?
No.

### CODE REVIEW

**Review by EricJames-NOAA — COMMENTED** [review]
@WenMeng-NOAA did you make changes to add 160m and 320m wind components in this PR as in my PR #693?  I'm not seeing those changes here.

I think it sounds like a good idea to sync the updates of the sndepac calculation back to the offline post.  If you can add it to your PR, that would be great.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA did you make changes to add 160m and 320m wind components in this PR as in my PR #693? I'm not seeing those changes here.
> 
> I think it sounds like a good idea to sync the updates of the sndepac calculation back to the offline post. If you can add it to your PR, that would be great.

@EricJames-NOAA This PR is for updating inline post interface with the changes from offline post interface. The changes for 160 and 320m wind components will be included in inline post with submodule upp revision upgrade in this PR.

**Review by EricJames-NOAA — APPROVED** [review]
Looks good!

**Comment by DusanJovic-NOAA** [comment]
Are there regression tests in ufs-weather-model that run with gocart_on, gccpp_on or nasa_on?

**Comment by DusanJovic-NOAA** [comment]
I see huge code duplication between post_fv3.f90  and INITPOST_NETCDF.f in UPP, for example code that computes  various PM concentration. All computations should be in done in the post library not here or in INITPOST. The only purpose of this module (post_fv3) is to pass model data to post library not to perform diagnostic computations. Similarly the purpose of INITPOST_NETCDF should be just to read model data from external file not to perform diagnostic computations. Maintaining very similar or exactly the same code (non trivial code) at to places is very error prone and in my opinion unnecessary.

**Comment by WenMeng-NOAA** [comment]
> Are there regression tests in ufs-weather-model that run with gocart_on, gccpp_on or nasa_on?

I am not sure. From my testing, I didn't see gocart_on, gccpp_on and nasa_on.  @zhanglikate @junwang-noaa Do you know that?

**Comment by WenMeng-NOAA** [comment]
> I see huge code duplication between post_fv3.f90 and INITPOST_NETCDF.f in UPP, for example code that computes various PM concentration. All computations should be in done in the post library not here or in INITPOST. The only purpose of this module (post_fv3) is to pass model data to post library not to perform diagnostic computations. Similarly the purpose of INITPOST_NETCDF should be just to read model data from external file not to perform diagnostic computations. Maintaining very similar or exactly the same code (non trivial code) at to places is very error prone and in my opinion unnecessary.

@DusanJovic-NOAA Thanks for the good suggestion. From UPP code management perspective, I totally agree with you. I am looking into the UPP code, this kind of enhancement might be in the interfaces of offline post for nemsio (GEFS V12) and netcdf (GFS17/GEFS12) and the interface of inline post. Given the resource constraints from UPP, I would suggest the effort starts after nemsio interface removal from UPP. Please let me know your comments on my proposal. @zhanglikate may chime in since she is the main developer for aerosol/chemical fields in UPP.

**Comment by zhanglikate** [comment]
> > Are there regression tests in ufs-weather-model that run with gocart_on, gccpp_on or nasa_on?
> 
> I am not sure. From my testing, I didn't see gocart_on, gccpp_on and nasa_on. @zhanglikate @junwang-noaa Do you know that?

There is no regression test for gocart_on option now since this is the GEFS-Aerosols model. I am still working on create the regression test for gccpp_on since this part has not been merge to current UFS model. For nasa_on, which is for current UFS-Aerosols model, not sure @junwang-noaa  or @lipan-NOAA may have tested it. Thanks.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA @junwang-noaa Should we let this pr move forward while additional regression tests for these gocart_on/gccpp_on/nasa_on may follow on in future? @WenMeng-NOAA I am wondering if we need to create issues pointed in this conversation. So we can track as PRs move.

**Comment by DusanJovic-NOAA** [comment]
We can merge this PR as it is now, and add regression tests and refactor later.

**Comment by WenMeng-NOAA** [comment]
> We can merge this PR as it is now, and add regression tests and refactor later.

I will create an issue regarding comments from @DusanJovic-NOAA and @junwang-noaa for inline post enhancement.

**Comment by zach1221** [comment]
Testing is complete on #1794. Once we have one more approval here, the merge process can begin. 
@BrianCurtis-NOAA @DusanJovic-NOAA

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by zach1221** [comment]
Ok, we have two approving reviews. @BrianCurtis-NOAA please feel free to merge this PR.

**Comment by BrianCurtis-NOAA** [comment]
Double checking hashes, upp isn't at the top of their develop and I was wondering if it's purposely lagged? @WenMeng-NOAA or @DusanJovic-NOAA know?

**Comment by WenMeng-NOAA** [comment]
> Double checking hashes, upp isn't at the top of their develop and I was wondering if it's purposely lagged? @WenMeng-NOAA or @DusanJovic-NOAA know?

@BrianCurtis-NOAA Yes, the recent commits from UPP/develop haven't being tested in in-line post yet.

**Comment by BrianCurtis-NOAA** [comment]
@WenMeng-NOAA Thank you! @jkbk2004 why was this merged before my question was answered?

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA upp develop hash continues to march, right? @WenMeng-NOAA https://github.com/NOAA-EMC/UPP/tree/baa77515f182eb6d6f2f8b57bd1e0ffb742761e8 hash is correct, right? Let me know if we need to revert.

**Comment by WenMeng-NOAA** [comment]
@jkbk2004 and @BrianCurtis-NOAA The upp  @baa7751 is the correct revision for this PR.

**Comment by DeniseWorthen** [comment]
@WenMeng-NOAA So just to be clear, it appears that UPP is the one repo that is not carried in UFS at the top of the develop branch.

I admit to not paying a lot of attention to the UPP updates---but why is UPP a special case? All other components point to the top of the develop branch of their respective repos.

**Comment by WenMeng-NOAA** [comment]
@DeniseWorthen When I submitted the FV3 PR, the upp revision is the top of develop branch. But this PR has been waiting over one month though I updated upp revisions several times. Meanwhile The UPP develop has been updated frequently. I don't want the upp commits from this week break UFS without inline post testing.

**Comment by DeniseWorthen** [comment]
@WenMeng-NOAA Thanks. But for all other components (eg. CICE, MOM6, CMEPS), we cannot update the develop branch for a component w/o simultaneously updating the UFS. They always go hand-in-hand. But it appears that for UPP, you can update develop at any time.

**Comment by WenMeng-NOAA** [comment]
@DeniseWorthen The UFS users can configure the UPP as a standalone utility (offline post) or sub component of FV3 (inline post) to post process model output. Some updates in UPP/develop are for offline post only and some updates will be applied in inline post with changes in the interface at FV3. I usually upgrade upp revision at FV3 every two months.

**Comment by DeniseWorthen** [comment]
@WenMeng-NOAA Thanks for the explanation.

**Pull request merged**
