### PR TITLE
Bugfixes for RRTMGP

### PR DESCRIPTION
**Pull request by dustinswales**
## Description
This PR contains a bug fix to all multiple threads for the RRTMGP radiation scheme in the ccpp-physics. There are no changes to any other FV3 components.

### Issue(s) addressed
Addresses [UWM:ccpp-physics Issue #59](https://github.com/ufs-community/ccpp-physics/issues/59)

## Testing

Tested on Cheyenne Intel.
Changes to ONLY control_p8_rrtmgp regression test baselines

### CODE REVIEW

**Comment by FernandoAndrade-NOAA** [comment]
Testing on #[1751 ](https://github.com/ufs-community/ufs-weather-model/pull/1751)has completed successfully and CCPP sub pr #[70 ](https://github.com/ufs-community/ccpp-physics/pull/70)has been merged in. @dustinswales could you revert gitmodules, update hash, and assign reviewers to approve?

**Comment by dustinswales** [comment]
@FernandoAndrade-NOAA Done, well everything but adding reviewers (I don't have permissions)

**Comment by FernandoAndrade-NOAA** [comment]
@jkbk2004 Could you add reviewers? It looks like I also don't have permissions

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by Qingfu-Liu — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
This PR is approved as well and ready for merging

**Pull request merged**
