### PR TITLE
Decrease the memory usage by MERRA2 for 6 times

### PR DESCRIPTION
**Pull request by AnningCheng-NOAA**
## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Provide a detailed description of what this PR does.  
What bug does it fix, or what feature does it add?  
Is a change of answers expected from this PR?  

read 2 month merra2 data instead of 12 months decrease memory usage by 6 times

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #423 
- fixes noaa-emc/fv3atm/issues/<420>
- fix # https://github.com/NCAR/ccpp-physics/pull/774
- fix# https://github.com/ufs-community/ufs-weather-model/pull/903

## Testing

How were these changes tested?   regression tests done in hera
What compilers / HPCs was it tested with?  standard compilers in hera
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  Yes
Have the ufs-weather-model regression test been run? On what platform?  in hera
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below. No
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first? No
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by junwang-noaa** [comment]
Thanks, the fv3atm branch looks correct now.

**Review by climbfuji — COMMENTED** [review]
Looks good to me. Will approve after regression testing is complete and the submodule pointer was updated.

**Review by junwang-noaa — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]
ccpp-physics hash is correct

**Comment by AnningCheng-NOAA** [comment]
Thanks all for the effort and have a great day!

**Pull request merged**
