### PR TITLE
Add ability to read increment files on native cubed sphere grid

### PR DESCRIPTION
**Pull request by DavidNew-NOAA**
## Description

This PR is a companion to GFDL Atmospheric Cubed Sphere PR #[342](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/342) which adds the ability to read increment files on native cubed sphere grid. Most of the technical details and motivation are in the description of that PR. This PR simply created the namelist option "increment_file_on_native_grid" to turn this feature on.

### Issue(s) addressed

N/A

## Testing

See description of GFDL Atmospheric Cubed Sphere PR #[342](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/342) for a summary of testing.

## Dependencies

- waiting on GFDL Atmospheric Cubed Sphere PR #[342](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/342)

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
According to description this PR depends on GFDL Atmospheric Cubed Sphere PR [#342](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/342). Please update `.gitmodules` to point to your atmos_cubed_sphere fork and update the atmos_cubed_sphere submodule.

**Comment by DavidNew-NOAA** [comment]
@DusanJovic-NOAA Done

**Comment by DusanJovic-NOAA** [comment]
You also need to update `.gitmodules` to point to your atmos_cubed_sphere fork. The current atmos_cubed_sphere hash ([953d582](https://github.com/DavidNew-NOAA/GFDL_atmos_cubed_sphere/commit/953d582e914e9cbc1190b4597a4245d055bab041)) doesn't exist in NOAA-GFDL/GFDL_atmos_cubed_sphere and recursive clone fails. I think that's the reason why the CI tests fail. https://github.com/NOAA-EMC/fv3atm/actions/runs/9303222835/job/25605091052?pr=837

Also I do not see the corresponding ufs-weather-model PR that points to this PR which is needed in order to run full ufs-wm regression tests.

**Comment by DavidNew-NOAA** [comment]
@DusanJovic-NOAA There was actually a compilation error in my atmos_cubed_sphere PR that did not show up with Intel but did with GCC. Now that I fixed it, the CI test passes without having to update .gitmodules. Should I still update it? I ask because won't that change have to be reverted back to point to the NOAA-EMC repo eventually?

Also, I just created a UFSWM PR that points to the FV3 hash for this PR: https://github.com/ufs-community/ufs-weather-model/pull/2304

**Comment by DavidNew-NOAA** [comment]
@DusanJovic-NOAA Is there anything I need to do to speed this PR along now that https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/342 is approved?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Is there anything I need to do to speed this PR along now that [NOAA-GFDL/GFDL_atmos_cubed_sphere#342](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/342) is approved?

@jkbk2004 Please schedule this PR for merge.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by zach1221** [comment]
@DavidNew-NOAA cubed-sphere PR-342  is merged. Please update the .gitmodule url, and hash.
Hash: https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/commit/ac3055eff06099d61cd65e18bc4f0353ffd83f46

**Review by jkbk2004 — APPROVED** [review]

**Comment by zach1221** [comment]
@jkbk2004 please merge this PR.

**Pull request merged**
