### PR TITLE
Feature/ccpp codeowners

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Description

Add codeowners in ccpp/physics for files that have known Points of Contact

### Issue(s) addressed

https://github.com/NCAR/ccpp-physics/pull/804

## Testing

Some test PRs were run to ensure the CODEOWNERS functionality worked as intended via test files. Also, the points of contact were alerted to this impending change.

It is impossible for this to change the regression test results, so those tests were not run.

## Dependencies

None.

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]
ccpp physics needs to point to NCAR main branch after the ccpp physics code is merged.

**Review by climbfuji — APPROVED** [review]
Please remember to update the ccpp-physics submodule pointer and to revert `.gitmodules`. Thanks for making the changes to `CODEOWNERS` in ccpp-physics!

**Comment by climbfuji** [comment]
Please add ccpp-physics PR to the `dependencies` section.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
@SamuelTrahanNOAA I merged the ccpp-physics PR, new hash is 4bb6e8d. Please update your fv3atm PR.

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA I merged the ccpp-physics PR, new hash is 4bb6e8d. Please update your fv3atm PR.

This is now done.

**Pull request merged**
