### PR TITLE
Introduce namelist flag xr_cnvcld to control if suspended grid-mean convective cloud condensate should be included in cloud fraction and optical depth calculation in radiation in the GFS suite.

### LINKED ISSUE #2184: Address convection/cloud/radiation interaction at coarse resolution
## Description
GSL colleagues found a drift in SST in coupled forecasts done at C96 resolutions.

We identified this to be related to convection/cloud/radiation interaction - when suspended convective clouds are passed to the Xu-Randall cloud fraction and/or optical depth calculation we get this drift in SSTs in coupled simulations. The problem does not occur at C192, C384, C768 and C1152. 

## Solution

Add a namelist flag to control in which application this convection/cloud/radiation coupling should occur.

### PR DESCRIPTION
**Pull request by lisa-bengtsson**
## Description

This PR introduces namelist flag xr_cnvcld to control if suspended grid-mean convective cloud condensate should be included in cloud fraction and optical depth calculation in radiation in the GFS suite.

The default setting is .true. so all regression tests passes (on Hera). We recommend using .false. for C96 resolution. 

Background:
Shan Sun, at GSL found the coupled SFS simulations (HR3 tag) at C96 have a drift in SST, not seen in C192 or C384. And not seen in P8 tag at C96 resolution. 

I proposed that it is likely related to the cloud/convection/radiation interaction introduced in HR1 causing a feedback loop at when grid-mean suspended convective clouds are added to the cloud fraction at coarse resolution. Sensitivity tests showed that is the case. In discussion with Jongil Han, Ruiyu Sun and Fanglin Yang, EMC we propose to add a namelist flag that can be used for tuning at different applications (resolutions)

From Shan Sun, GSL: 
image

### Issue(s) addressed
- fixes https://github.com/ufs-community/ufs-weather-model/issues/2184

## Testing

Regression tests on Hera pass, not new baselines required 

## Dependencies

- waiting on https://github.com/ufs-community/ccpp-physics/pull/184

### CODE REVIEW

**Review by jkbk2004 — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by grantfirl** [comment]
@lisa-bengtsson https://github.com/ufs-community/ccpp-physics/pull/184 was merged, so this is ready to revert the changes in .gitmodules and update the ccpp-physics submodule pointer.

**Comment by zach1221** [comment]
> @lisa-bengtsson [ufs-community/ccpp-physics#184](https://github.com/ufs-community/ccpp-physics/pull/184) was merged, so this is ready to revert the changes in .gitmodules and update the ccpp-physics submodule pointer.

@grantfirl it looks like Lisa is out of office this week until Friday. Could @DusanJovic-NOAA possibly make these updates?

**Comment by jkbk2004** [comment]
@grantfirl @zach1221 let me see if I have permission.

**Comment by grantfirl** [comment]
> > @lisa-bengtsson [ufs-community/ccpp-physics#184](https://github.com/ufs-community/ccpp-physics/pull/184) was merged, so this is ready to revert the changes in .gitmodules and update the ccpp-physics submodule pointer.
> 
> @grantfirl it looks like Lisa is out of office this week until Friday. Could @DusanJovic-NOAA possibly make these updates?

Ya, whomever has write access to her fork could do this. I don't know who does though. Worst case scenario, someone (me or someone else) could create a new branch and PR that is identical for merging.

**Comment by lisa-bengtsson** [comment]
> > > @lisa-bengtsson [ufs-community/ccpp-physics#184](https://github.com/ufs-community/ccpp-physics/pull/184) was merged, so this is ready to revert the changes in .gitmodules and update the ccpp-physics submodule pointer.
> > 
> > 
> > @grantfirl it looks like Lisa is out of office this week until Friday. Could @DusanJovic-NOAA possibly make these updates?
> 
> Ya, whomever has write access to her fork could do this. I don't know who does though. Worst case scenario, someone (me or someone else) could create a new branch and PR that is identical for merging.

I can do it now, give me one second.

**Comment by jkbk2004** [comment]
@lisa-bengtsson I pushed update. Can you check?

**Comment by lisa-bengtsson** [comment]
@jkbk2004 ok, thank you! That looks good to me.

**Comment by zach1221** [comment]
> @lisa-bengtsson I pushed update. Can you check?

Thanks, @jkbk2004 ! Looks good to me as well. We're ready now to merge.

**Pull request merged**
