### PR TITLE
Consistent names in the meta files

### PR DESCRIPTION
**Pull request by ShanSunNOAA**
Changing standard/long names to be consistent with variable names. No changes in output.

It corresponds to ccpp PR #456.

### CODE REVIEW

**Comment by climbfuji** [comment]
The commit history looks good now. I would have preferred using `cmm_water` instead of `cmm_wat` (same for all others), because `ice` and `land` are spelled out. But I will defer this decision to others.

**Comment by ShanSunNOAA** [comment]
Hi Dom,

I see your point. Although names of ice, lnd and wat are used in CCPP, they
were ice, land and ocean in GFS_typedefs. I will replace wat by water only
in GFS_typedefs.

Thanks,
Shan

**Comment by climbfuji** [comment]
> Hi Dom, I see your point. Although names of ice, lnd and wat are used in CCPP, they were ice, land and ocean in GFS_typedefs. I will replace wat by water only in GFS_typedefs. Thanks, Shan
> […](#)

Thanks - and GFS_typedefs.meta (in the square brackets only = the local names), please.

**Comment by ShanSunNOAA** [comment]
Done. Please let me know if you have any suggestions.

Thanks,
Shan

**Comment by climbfuji** [comment]
@shansun6 is this PR still applicable after the flake changes are merged (#141 and PRs listed in there)?

**Comment by ShanSunNOAA** [comment]
Hi Dom,

What should I do here? Could you give me some options? Thanks,

Shan

**Comment by climbfuji** [comment]
> Hi Dom, What should I do here? Could you give me some options? Thanks, Shan
> […](#)

I am just wondering if this PR should still be merged or closed, given that a consensus was reached on how to best implement flake.

**Comment by ShanSunNOAA** [comment]
It appears that flake cannot run with s2s - the coupled model crashed even
when flake is turned off. There are email exchanges among Yihua, Moorthi
and Jun today, trying to figure it out. I guess flake needs to work with
the coupled model before this PR can be merged? Jun should know more on
this.

Thanks,
Shan

**Comment by climbfuji** [comment]
The corresponding ccpp-physics PR https://github.com/NCAR/ccpp-physics/pull/456 was closed in agreement with @shansun6. Please close this PR, too.

**Pull request closed without merging**
