### PR TITLE
RRTMGP improvements

### PR DESCRIPTION
**Pull request by dustinswales**
This PR contains changes to the FV3 infrastructure to use new RRTMGP capabilities, see PR #446 (NCAR/ccpp-physics#446).

### CODE REVIEW

**Comment by climbfuji** [comment]
These changes look like a lot of work but pretty straightforward.

**Comment by climbfuji** [comment]
> These changes look like a lot of work but pretty straightforward.

I am missing the (temporary) change to `.gitmodules` for the ccpp-physics submodule pointer, though.

**Comment by climbfuji** [comment]
Can you pull the fv3atm develop branch in, please and push it to this branch?

**Comment by dustinswales** [comment]
> Can you pull the fv3atm develop branch in, please and push it to this branch?

I did. It is up to date with EMC, aada7736c51b5f486b8d9251933184d70d9bb494

**Comment by climbfuji** [comment]
> > Can you pull the fv3atm develop branch in, please and push it to this branch?
> 
> I did. It is up to date with EMC, [aada773](https://github.com/NOAA-EMC/fv3atm/commit/aada7736c51b5f486b8d9251933184d70d9bb494)

The last commit to this PR is from 23 hours ago (https://github.com/NOAA-EMC/fv3atm/pull/151/commits/a81a808b8e6f850ac3459d902a604159b8e8a8d2). Maybe you didn't push the changes?

**Comment by dustinswales** [comment]
> > > Can you pull the fv3atm develop branch in, please and push it to this branch?
> > 
> > 
> > I did. It is up to date with EMC, [aada773](https://github.com/NOAA-EMC/fv3atm/commit/aada7736c51b5f486b8d9251933184d70d9bb494)
> 
> The last commit to this PR is from 23 hours ago ([a81a808](https://github.com/NOAA-EMC/fv3atm/commit/a81a808b8e6f850ac3459d902a604159b8e8a8d2)). Maybe you didn't push the changes?

Hmm. https://github.com/dustinswales/fv3atm/commits/develop

**Comment by climbfuji** [comment]
Maybe just the time information is wrong. But we need to fix the conflict in ufs-weather-model as well. Once we have that, I can at least check out everything recursively to see that we are up to date.

**Comment by dustinswales** [comment]
This conflict is puzzling to me. I didn't see it when I pulled/pushed. I still can't see it in my local repo.

**Comment by climbfuji** [comment]
> This conflict is puzzling to me. I didn't see it when I pulled/pushed. I still can't see it in my local repo.

Let me try ...

**Comment by climbfuji** [comment]
Please merge https://github.com/dustinswales/ufs-weather-model/pull/4.

**Comment by climbfuji** [comment]
Regression testing on hera.intel and hera.gnu against _existing_ baselines. All non-RRTMGP tests pass, all RRTMGP tests fail because of missing baselines (but they all run to completion).

[rt_hera_gnu.log](https://github.com/NOAA-EMC/fv3atm/files/5038045/rt_hera_gnu.log)
[rt_hera_gnu_against_existing_baseline_fail_test.log](https://github.com/NOAA-EMC/fv3atm/files/5038047/rt_hera_gnu_against_existing_baseline_fail_test.log)
[rt_hera_intel.log](https://github.com/NOAA-EMC/fv3atm/files/5038048/rt_hera_intel.log)
[rt_hera_intel_against_existing_baseline_fail_test.log](https://github.com/NOAA-EMC/fv3atm/files/5038049/rt_hera_intel_against_existing_baseline_fail_test.log)

**Review by SMoorthi-emc — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]
These changes look good to me, approved.

**Review by hsinmulin-NOAA — APPROVED** [review]
Approved as it is if pass the regression test.

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
