### PR TITLE
Convective Reflectivity

### PR DESCRIPTION
**Pull request by ericaligo-NOAA**
## Description

@RuiyuSun and I compute convective reflectivity for Thompson or NSSL microphysics and with GF deep, shallow or SAS deep convection. I removed the calculation that was in cu_gf_driver_post.F90 and cu_gf_driver_post.meta, and associated parameters, and added the code to GFS_MP_generic_post.F90.  The 3D refl_10cm array will be changed. In the process of creating a new baseline. I had to modify regional.nml.IN and change imfhalcnv and imfdeepconv from 2 to -1 otherwise the code would try to calculate convective reflectivity despite no calls for deep/shallow convection.

[RegressionTests_hera.log](https://github.com/NOAA-EMC/fv3atm/files/13420642/RegressionTests_hera.log)
[RegressionTests_hera_newbaseline.log](https://github.com/NOAA-EMC/fv3atm/files/13420643/RegressionTests_hera_newbaseline.log)

### Issue(s) addressed
https://github.com/ufs-community/ufs-weather-model/issues/1968
https://github.com/NOAA-EMC/fv3atm/issues/716
https://github.com/ufs-community/ccpp-physics/issues/123

## Testing

Tested initially in the RRFS configuration on hera.
RTs run on orion with intel compiler.

Since refl_10cm will change, running new baseline on orion. 

## Dependencies

None

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
Please update the title of this PR to something more descriptive.

**Review by jkbk2004 — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by Qingfu-Liu — APPROVED** [review]

**Comment by grantfirl** [comment]
@ericaligo-NOAA https://github.com/ufs-community/ccpp-physics/pull/129 was merged. Please revert the changes to .gitmodules and point to the latest commit in the ufs/dev branch of ccpp/physics: https://github.com/ufs-community/ccpp-physics/commit/c0aa212dbc255ac5d77934c3cd6283c994bbfd99

**Comment by ericaligo-NOAA** [comment]
Reverted changes to .gitmodules, pointed to ufs/dev and pushed to branch.

**Comment by zach1221** [comment]
@ericaligo-NOAA I think your ccpp-physics hash still needs to be pointed to hash: c0aa212dbc255ac5d77934c3cd6283c994bbfd99

**Comment by DeniseWorthen** [comment]
@ericaligo-NOAA You had it right the first time, but I think you had neglected to update the ccpp hash in your FV3atm branch. So you want gitmodules to use ccpp ufs/dev and make sure that your FV3 branch is using the hash at the top of ufs/dev.

**Comment by zach1221** [comment]
Ok, we're good now. Feel free to merge as well, if you can @jkbk2004 .

**Pull request merged**
