### PR TITLE
Update surface net heat fluxes for AQM coupling (was #575)

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
Helping @rmontuoro out with this PR, taking over to update to latest devel

## Description

This PR introduces CCPP updates to rectify the formulation of surface net heat fluxes used for AQM coupling.

### Issue(s) addressed

- fixes NCAR/ccpp-physics/issues/945

## Testing

These changes were tested on the Hera/Intel platform.

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

- waiting on ncar/ccpp-physics/pull/962
- closes #575

### CODE REVIEW

**Comment by grantfirl** [comment]
@BrianCurtis-NOAA https://github.com/NCAR/ccpp-physics/pull/962 has been merged

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA [cpp#962](https://github.com/NCAR/ccpp-physics/pull/962) was merged. we can start merging in this pr with ccpp hash pointer update.

**Comment by BrianCurtis-NOAA** [comment]
It's ready.

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA @ChunxiZhang-NOAA can we have final approvals to merge in?

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Pull request merged**
