### PR TITLE
A merra2 interpolation bug found by running RRFS

### PR DESCRIPTION
**Pull request by AnningCheng-NOAA**
## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Provide a detailed description of what this PR does.  
What bug does it fix, or what feature does it add?  
A merra2 interpolation bug
Is a change of answers expected from this PR?  
Yes. Changes are expected in all conus_13km related RTs when one inner model level is equal to one of the MERRA2 pressure level. 

### Issue(s) addressed
[#152](https://github.com/ufs-community/ccpp-physics/issues/152)
Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #<152>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested?  
RTS in hera
What compilers / HPCs was it tested with?  
hera intel
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
yes
Have the ufs-weather-model regression test been run? On what platform?  
full RTs in hera
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
Yes. New baselines are needed for all conus_13km related tests. Namely:
conus13km_2threads  conus13km_debug           conus13km_debug_decomp  conus13km_decomp            conus13km_restart
conus13km_control   conus13km_debug_2threads  conus13km_debug_qr      conus13km_radar_tten_debug  conus13km_restart_mismatch
- Please commit the regression test log files in your ufs-weather-model branch
yes. Committed in https://github.com/ufs-community/ufs-weather-model/pull/2082

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<750>
- waiting on https://github.com/ufs-community/ufs-weather-model/pull/2082
- waiting on [PR#153](https://github.com/ufs-community/ccpp-physics/pull/153)

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@AnningCheng-NOAA there is a CI update in FV3ATM, would you please sync your fv3atm branch? Thanks

**Review by junwang-noaa — APPROVED** [review]

**Comment by AnningCheng-NOAA** [comment]
Jun, done.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by grantfirl** [comment]
@AnningCheng-NOAA https://github.com/ufs-community/ccpp-physics/pull/153 was merged. You're ready to revert the change to .gitmodules and `git add` the latest commit of the ufs/dev branch of ccpp-physics: https://github.com/ufs-community/ccpp-physics/commit/a492addf860d29d797bca488f53d39b260584924

**Comment by jkbk2004** [comment]
@AnningCheng-NOAA physics pr was merge. Can you update hash and revert change in gitmodules ? Correct hash is https://github.com/ufs-community/ccpp-physics/commit/a492addf860d29d797bca488f53d39b260584924

**Comment by AnningCheng-NOAA** [comment]
Thank you all for the effort!

**Pull request merged**
