### PR TITLE
Fractional landmask: Changing ice fraction definition

### PR DESCRIPTION
**Pull request by ShanSunNOAA**
PLACEHOLDER

### CODE REVIEW

**Comment by climbfuji** [comment]
This PR has been pulled into https://github.com/NCAR/fv3atm/pull/31 and will be merged into NCAR's dtc/develop first, before this gets merged into develop.

**Comment by climbfuji** [comment]
@shansun6 can you please update the description of this PR? Thanks.

**Comment by ShanSunNOAA** [comment]
Hi Dom,

How about this:

Changing the definition of ice fraction on the FV3 grid to "ratio of ice
area with respect to ocean area (instead of whole cell)".

Thanks,
Shan

**Comment by climbfuji** [comment]
> Hi Dom, How about this: Changing the definition of ice fraction on the FV3 grid to "ratio of ice area with respect to ocean area (instead of whole cell)". Thanks, Shan
> […](#)

Thanks, sounds good to me.

**Comment by climbfuji** [comment]
Note: this PR and/or https://github.com/NCAR/ccpp-physics/pull/398 do change the answer of the NoahMP regression tests for both IPD and CCPP (but in the same way, i.e. IPD and CCPP are still bit-for-bit identical between each other). See this note:

https://github.com/NCAR/ufs-weather-model/pull/28#issuecomment-599301946

**Comment by climbfuji** [comment]
This PR does not show up as merged, because it was pulled into NCAR dtc/develop first (see https://github.com/NCAR/ufs-weather-model/pull/28) and later merged back to EMC develop (see https://github.com/NOAA-EMC/fv3atm/pull/81). Therefore, this PR was effectively merged and should be closed.

**Comment by junwang-noaa** [comment]
Merged to develop branch in #81 , close PR

**Pull request closed without merging**
