### PR TITLE
Quartet of bug fixes for: c3 scheme, quilting restart with 32-bit physics, and string length mismatch in dycore plus PR #705 and #699

### LINKED ISSUE #112: CLM Lake restarts nine 3D fields that are constant
# Description

These fields in the CLM Lake model are constant:

- lake_z3d
- lake_dz3d
- lake_soil_watsat3d
- lake_csol3d
- lake_soil_tkmg3d
- lake_soil_tkdry3d
- lake_soil_tksatu3d
- lake_clay3d
- lake_sand3d

The later seven are 2D arrays that are needlessly duplicated in the vertical (lake k) dimension. The first two are 3D. All of these are sparse arrays, zero everywhere except lake points.

All nine should be removed.

## Steps to Reproduce

1. Read the code. The lakeini in clm_lake.f90 calculates those variables. They're never modified after that.

## Additional Context

The CLM Lake Model is taking up too much disk space in the RRFS. Removing these nine variables would reduce that problem.

Problem identified by @hu5970 and @tanyasmirnova

### LINKED ISSUE #694: Unnecessary call to recover_fields for restart files can cause crashes.
## Description
While trouble-shooting https://github.com/ufs-community/ufs-weather-model/issues/1882, @junwang-noaa and @DusanJovic-NOAA discovered an unnecessary call to recover_fields. It only needs to be called for history files, not restart files. Presently, the call is done for both.

When 32-bit physics is enabled, the quilting restart will frequently abort on Hera with the gnu compiler in debug mode. It encounters a floating-point exception due to corrupted longitudes in recover_fields. This only happens for restart files. Removing the call eliminates that crash. Unfortunately, the model still crashes due to another, unknown, bug.

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. Run the `conus13km_debug` test with quilting restart and the gnu compiler on Hera. You will need https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/280 to avoid another crash.
2. Keep running until it fails in recover_fields. (It may fail earlier, in InitializeAdvertise.)

## Additional context
The broader problem of quilting restart failing for 32-bit physics is discussed here:

- https://github.com/ufs-community/ufs-weather-model/issues/1882

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Description

Bug fixes:

1. *The write component no longer calls recover_fields for restart files.* (From @DusanJovic-NOAA.) Doing so causes sporadic crashes due to corrupted longitudes when 32-bit physics is used. This only happens for restart files, who don't need recover_fields anyway. Hence, this PR restricts that call to history files.
2. *Correct a string length mismatch in the dycore.* This causes an abort when the gnu compiler is run with debug flags turned on. One of the checks enabled is to abort on standard violations of this type.
3. *Changes some subroutine array argument declarations so the c3 scheme can handle null pointers.* This is required by the CCPP coding standards anyway, for that very reason. Without this change, the FV3_HRRR_c3 suite crashes with the gnu compiler.
4. *Initialize arrays in dycore.* (From @DusanJovic-NOAA.) Two arrays in the dycore were not initialized. That caused crashes in the quilting restart when 32-bit physics is used.

Included in this PR are:

- #705 
- #699 
- https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/276
- https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/285

### Issue(s) addressed

- fixes https://github.com/NOAA-EMC/fv3atm/issues/694
- fixes https://github.com/ufs-community/ccpp-physics/issues/112

#### How were these changes tested?  
New or improved ufs-weather-model regression tests

#### What compilers / HPCs was it tested with?  

jet, hera, cheyenne, hercules, orion, and cactus (wcoss2)

#### Are the changes covered by regression tests?

Some ufs-weather-model regression tests are added or modified.

#### Have the ufs-weather-model regression test been run? On what platform?  

jet, hera, cheyenne, hercules, orion, and cactus (wcoss2)

#### Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.

Yes. All tests with FV3 will change due to https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/276

#### Please commit the regression test log files in your ufs-weather-model branch

Will do.

## Dependencies

- waiting on https://github.com/ufs-community/ccpp-physics/pull/102
- waiting on https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/280

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
I've merged #701 into this PR since the UFS code managers plan to merge both simultaneously.

Also, I've merged #697 into this PR since that one is expected to go in first.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
@haiqinli - Please confirm I merged your changes correctly.

**Comment by haiqinli** [comment]
@SamuelTrahanNOAA Your merging looks good to me. Thank you very much!

**Comment by grantfirl** [comment]
@SamuelTrahanNOAA https://github.com/ufs-community/ccpp-physics/pull/102 was merged. Please prepare this one for merge.

**Comment by SamuelTrahanNOAA** [comment]
This PR is ready for merge.

- atmos_cubed_sphere is the head of the dev/emc branch of GFDL_atmos_cubed_sphere
- ccpp/physics is the head of the ufs/dev branch of ccpp-physics
- .gitmodules matches the current HEAD of develop

**Pull request merged**
