### PR TITLE
support for removal of GFS DDTs from CCPP physics

### PR DESCRIPTION
**Pull request by grantfirl**
## Description

This PR adds new variables and metadata in GFS_typedefs.[F90,meta] to work with the changes in ccpp-physics where GFS derived data types (DDTs) are removed in favor of individual CCPP variables. This change allows greater adherence to CCPP requirements and potentially greater interoperability by removing GFS DDTs from existing CCPP physics. Most of the changes in ccpp-physics are related to interstitial schemes related to radiation.

Update for 2020/09/03:
- added active metadata attribute to diagnostic tendency slices that were not given this attribute in previous PR
- addressed issue https://github.com/NOAA-EMC/fv3atm/issues/159, although someone with access still needs to copy the diag_table in that issue (and copied below in Dependencies) into the RT input when this PR undergoes final regression testing.

## Testing
See comments below.

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/493
[diag_table_gsd_ruc_diag3d.zip](https://github.com/NOAA-EMC/fv3atm/files/5171665/diag_table_gsd_ruc_diag3d.zip) (should be copied into RT input files for the fv3_ccpp_gsd_diag3d_debug test)

### CODE REVIEW

**Comment by grantfirl** [comment]
All RTs with WW3=Y failed again (using ecflow) with segmentation faults this time. This should be unrelated to this pull request.

Tested together with https://github.com/NCAR/ccpp-physics/pull/493
[rt_GFS_DDT_removal.log](https://github.com/NOAA-EMC/fv3atm/files/5142898/rt_GFS_DDT_removal.log)

**Comment by grantfirl** [comment]
Subsequent tests run on Hera.intel by @climbfuji all passed, so this should be ready for review and/or entry into the commit queue.

**Comment by climbfuji** [comment]
This PR was pulled into https://github.com/NCAR/fv3atm/pull/64, which merges the changes into NCAR's feature/transition-to-capgen-1 branch. These changes will come to develop in the next couple of weeks.

**Comment by climbfuji** [comment]
All changes from this PR were included in https://github.com/NOAA-EMC/fv3atm/pull/186.

**Pull request closed without merging**
