### PR TITLE
Remove legacy print statements from io/FV3GFS_io.F90

### LINKED ISSUE #226: Cleanup of FV3GFS_io.F90
Removing print statements in FV3GFS_io.F90: Lines 1082-1084; 1087-1088; 1096-1098; 1101-1102.  No change in results.

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

As the title says. Remove print statements used during the development phase, no longer needed.

### Issue(s) addressed

Fixes https://github.com/NOAA-EMC/fv3atm/issues/226.

## Testing

This PR will be pullet into the Thompson subcycling PR and merged as part of it.

### CODE REVIEW

**Review by ShanSunNOAA — CHANGES_REQUESTED** [review]
Please remove lines 1067 & 1081 (in the original file) as well. Thanks!

**Comment by climbfuji** [comment]
> Please remove lines 1067 & 1081 (in the original file) as well. Thanks!

Done, please check if it is ok now. I am running the full regression tests on hera again just to be 100% sure none of the results change. I'll pull this PR into the Thompson subcycling PR tomorrow in the tutorial to demonstrate how to do that.

**Comment by ShanSunNOAA** [comment]
Looks good to me. Thanks for doing this.

**Comment by climbfuji** [comment]
> Looks good to me. Thanks for doing this.

Thanks, Shan. I ran the full regression tests on hera.intel and hera.gnu, and all tests passed. See attach log.

[rt_hera_intel_verify_against_existing.log](https://github.com/NOAA-EMC/fv3atm/files/6618372/rt_hera_intel_verify_against_existing.log)
[rt_hera_gnu_verify_against_existing.log](https://github.com/NOAA-EMC/fv3atm/files/6618375/rt_hera_gnu_verify_against_existing.log)

**Comment by ShanSunNOAA** [comment]
Great news - thanks for your help with this!

Shan

**Comment by climbfuji** [comment]
Code has been committed in https://github.com/NOAA-EMC/fv3atm/pull/328.

**Pull request closed without merging**
