### PR TITLE
fix the number of 2d fields  nsfcprop2d

### PR DESCRIPTION
**Pull request by HelinWei-NOAA**
This is the fix for the [issue ](https://github.com/NOAA-EMC/fv3atm/issues/418)

### CODE REVIEW

**Comment by climbfuji** [comment]
@HelinWei-NOAA I pulled your changes in my next PR https://github.com/NOAA-EMC/fv3atm/pull/417. We can close this PR once #417 is merged.

**Comment by HelinWei-NOAA** [comment]
Great. Thanks.

**Review by junwang-noaa — APPROVED** [review]
Looks good to me

**Comment by junwang-noaa** [comment]
The code changes were committed in PR#417, The PR is closed.

**Pull request closed without merging**
