### PR TITLE
Release/public v3

### PR DESCRIPTION
**Pull request by mark-a-potts**
This PR pulls in Grant's changes and an updated version of ccpp-physics release/public-v6 for use with SRW release/public-v2. 

This addresses issue #547 

## Testing

Testing has currently been done at the SRW application level. Further testing will be done.

## Dependencies

This PR will be tested with the release/public-v3 branch of the ufs-weather-model

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Review by daniel-hildebrandt — APPROVED** [review]

**Comment by grantfirl** [comment]
@mark-a-potts By merging this on top of the existing NOAA-EMC/release/public-v3 branch, won't it still contain some code that we don't want in there? In particular, https://github.com/NOAA-EMC/fv3atm/commit/1e9c3da5e0cc9efcc434cb3a2ea08a9f521939d2. Can we just overwrite the NOAA-EMC/release/public-v3 branch with NOAA-EPIC:release/public-v3 branch? Or, am I misunderstanding what git will do here?

**Comment by mark-a-potts** [comment]
I was not sure about that, tbh. If we can just re-create the branch, that would probably be best.

**Comment by jkbk2004** [comment]
@mark-a-potts @grantfirl I agree with recreating branches. Certainly, the approach is bypassing the current emc repository maintenance rule. But we have to control the gaps we already have regarding the release. Fortunately, Mark has already emc group account ownership. So no problem to exercise the privilege if we all agree. We can put specific release branch name this time like release/public-v3_srw. Actually, same thing is possible on ufs-wm side: release/public-v3_srw. Or release/public-srw-v3 ?

**Comment by mark-a-potts** [comment]
I will delete the old one and push the correct branch, then.

**Pull request closed without merging**
