### PR TITLE
Enable AOD in AQM

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## Description
These changes will allow AOD with the AQM.

### Issue(s) addressed
Addresses NOAA-EMC/AQM/issues/23

## Testing
How were these changes tested? Intel/Hera  
Are the changes covered by regression tests? Not yet, not needed.  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? No

## Dependencies
None

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
This will start testing in UFSWM shortly. It's a small change that shouldn't impact anything other than AQM, please let me know if you feel otherwise before I get too far into testing.

**Comment by BrianCurtis-NOAA** [comment]
@rmontuoro Could you please merge in the latest updates from NOAA-EMC/fv3atm develop branch?

**Comment by rmontuoro** [comment]
@BrianCurtis-NOAA - done.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
We're ready for reviews / merge on the UFSWM side.

**Comment by BrianCurtis-NOAA** [comment]
@DusanJovic-NOAA please add a second reviewer.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
