### PR TITLE
Revert "Feature/ufs nst"

### PR DESCRIPTION
**Pull request by junwang-noaa**
Reverts NOAA-EMC/fv3atm#255.  Does not point to the top of NCAR master revision: 990b9d041

### CODE REVIEW

**Review by XuLi-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
Do not merge this - there is a much simpler way. Let me do it ...

**Comment by climbfuji** [comment]
Replaced  by https://github.com/NOAA-EMC/fv3atm/pull/274.

**Comment by DusanJovic-NOAA** [comment]
Can we delete this branch (revert-255-feature/ufs-nst)?

**Comment by XuLi-NOAA** [comment]
I am not sure what this branch for but it can be deleted, I think. Let others confirm.

**Pull request closed without merging**
